import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
const {CATBOX_API,CATBOX_GIF_LIMIT,readGIF,catboxForm,parseCatboxURL,uploadGIF,CatboxUploads}=createRequire(import.meta.url)('../electron/catbox-upload.cjs');
const tiny=Buffer.from('R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7','base64');
const url='https://files.catbox.moe/abc123.gif';
async function fixture(t,bytes=tiny){const dir=await fs.mkdtemp(path.join(os.tmpdir(),'mdlxl-catbox-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));const file=path.join(dir,'preview.gif');await fs.writeFile(file,bytes);return file;}
const response=(body=url,status=200)=>new Response(body,{status});
for(const signature of ['GIF87a','GIF89a'])test(signature+' is accepted and uploaded byte-for-byte anonymously',async t=>{
 const bytes=Buffer.from(tiny);bytes.write(signature);const file=await fixture(t,bytes);let calls=0;
 const result=await uploadGIF(file,{fetchImpl:async(endpoint,options)=>{calls++;assert.equal(endpoint,CATBOX_API);assert.equal(options.method,'POST');assert.equal(options.credentials,'omit');assert.equal(options.redirect,'error');assert.equal(options.headers,undefined);assert.deepEqual([...options.body.keys()],['reqtype','fileToUpload']);assert.equal(options.body.get('reqtype'),'fileupload');assert.equal(options.body.has('userhash'),false);const blob=options.body.get('fileToUpload');assert.equal(blob.type,'image/gif');assert.deepEqual(Buffer.from(await blob.arrayBuffer()),bytes);return response('  '+url+'\n');}});
 assert.equal(result,url);assert.equal(calls,1);assert.deepEqual(await fs.readFile(file),bytes);
});
test('exactly 20 MiB is accepted',async t=>{const bytes=Buffer.alloc(CATBOX_GIF_LIMIT);tiny.copy(bytes);bytes[bytes.length-1]=0x3b;const file=await fixture(t,bytes);assert.equal((await readGIF(file)).length,CATBOX_GIF_LIMIT);assert.equal(catboxForm(bytes).get('fileToUpload').size,CATBOX_GIF_LIMIT);});
test('over 20 MiB is rejected before the request',async t=>{const file=await fixture(t);await fs.truncate(file,CATBOX_GIF_LIMIT+1);let called=false;await assert.rejects(uploadGIF(file,{fetchImpl:()=>{called=true;}}),error=>error.code==='too_large'&&/20 MB/.test(error.message));assert.equal(called,false);assert.equal((await fs.stat(file)).size,CATBOX_GIF_LIMIT+1);});
test('PNG renamed GIF and incomplete GIFs are rejected',async t=>{const file=await fixture(t,Buffer.from([137,80,78,71,13,10,26,10]));await assert.rejects(readGIF(file),{code:'invalid_gif'});await fs.writeFile(file,tiny.subarray(0,20));await assert.rejects(readGIF(file),{code:'invalid_gif'});});
test('missing and unreadable (directory) exports have a clear error',async t=>{const file=await fixture(t);await assert.rejects(readGIF(file+'.missing'),{code:'unreadable'});await assert.rejects(readGIF(path.dirname(file)),{code:'unreadable'});});
test('direct URL and surrounding whitespace are accepted',()=>{assert.equal(parseCatboxURL(url),url);assert.equal(parseCatboxURL('\n  '+url+' \r\n'),url);});
for(const body of ['Error uploading','<html>Denied</html>','http://files.catbox.moe/a.gif','https://evil.com/a.gif','https://files.catbox.moe.evil.com/a.gif','https://files.catbox.moe@evil.com/a.gif','https://user@files.catbox.moe/a.gif','https://files.catbox.moe/a.png','https://files.catbox.moe/a.gif?x=1',url+'\n'+url])test('unexpected response rejected: '+body,()=>assert.throws(()=>parseCatboxURL(body),{code:'unexpected_response'}));
test('HTTP failures remain distinct and do not retry',async t=>{const file=await fixture(t);let calls=0;await assert.rejects(uploadGIF(file,{fetchImpl:async()=>{calls++;return response('no',503);}}),error=>error.code==='http'&&/503/.test(error.message));assert.equal(calls,1);assert.deepEqual(await fs.readFile(file),tiny);});
test('network failure has useful classification and preserved cause',async t=>{const file=await fixture(t);const cause=Error('ENOTFOUND');await assert.rejects(uploadGIF(file,{fetchImpl:async()=>{throw cause;}}),error=>error.code==='network'&&error.cause===cause);});
test('timeout covers both request and response body without automatic retry',async t=>{const file=await fixture(t);let signal;await assert.rejects(uploadGIF(file,{timeoutMs:10,fetchImpl:async(_,options)=>{signal=options.signal;return new Promise(()=>{});}}),{code:'timeout'});assert.equal(signal.aborted,true);await assert.rejects(uploadGIF(file,{timeoutMs:10,fetchImpl:async()=>({ok:true,text:()=>new Promise(()=>{})})}),{code:'timeout'});});
test('duplicate upload prevention, success reuse, ownership, and clipboard formats',async t=>{const file=await fixture(t);let finish,calls=0;const store=new CatboxUploads({fetchImpl:async()=>{calls++;return new Promise(resolve=>{finish=()=>resolve(response());});}});const row=store.remember(1,{path:file,name:'preview.gif'});assert.throws(()=>store.get(2,row.exportId));assert.throws(()=>store.get(1,file));assert.throws(()=>store.link(1,row.exportId));const first=store.upload(1,row.exportId);await assert.rejects(store.upload(1,row.exportId),{code:'duplicate'});while(!finish)await new Promise(resolve=>setImmediate(resolve));finish();assert.equal(await first,url);assert.equal(await store.upload(1,row.exportId),url);assert.equal(calls,1);assert.equal(store.link(1,row.exportId),url);assert.equal(store.link(1,row.exportId,true),'[IMG]'+url+'[/IMG]');});
test('failed upload can be retried only with another explicit call',async t=>{const file=await fixture(t);let calls=0;const store=new CatboxUploads({fetchImpl:async()=>++calls===1?response('no',500):response()});const row=store.remember(1,{path:file});await assert.rejects(store.upload(1,row.exportId),{code:'http'});assert.equal(calls,1);assert.equal(await store.upload(1,row.exportId),url);assert.equal(calls,2);});
