import React,{useEffect,useRef,useState} from 'react';import {createRoot} from 'react-dom/client';
import GamePreview from '../app/GamePreview.jsx';import {DEFAULT_PREFERENCES} from '../src/preferences.js';import {parseParticleData,stringifyParticleData} from '../src/particle-data.js';import {particleRecipeDocument} from '../src/particle-recipes.js';
const ids=['wc3-838fc48f5ca1aa51639306d7','wc3-b77c9b1c56c50dec1ffcfd04','wc3-eb436de856fa4d1e5ddf2d62'],cases=[],recipes=[];
for(const id of ids){const recipe=parseParticleData(await window.desktop.particleRead(id)),doc=particleRecipeDocument(recipe),records=await window.desktop.particleAssets({sourceKey:recipe.sources[0].buildKey,dependencies:recipe.dependencies}),assets=new Map(records.filter(r=>r.bytes).map(r=>[r.name.toLowerCase(),r]));recipes.push({recipe,before:stringifyParticleData(recipe)});for(const [sequence,clip]of doc.model.Sequences.entries())if(/birth|stand|attack|spell|death|decay|dissipate/i.test(clip.Name)){for(const fraction of [.15,.5,.9])cases.push({id,model:doc.model,assets,sequence,time:clip.Interval[0]+(clip.Interval[1]-clip.Interval[0])*fraction,label:recipe.sources[0].logicalPath.split('\\').at(-1)+' · '+clip.Name+' · '+Math.round(fraction*100)+'%'});}}
const prefs={...DEFAULT_PREFERENCES,graphics:{...DEFAULT_PREFERENCES.graphics,pauseWhenHidden:false},viewportAppearance:{...DEFAULT_PREFERENCES.viewportAppearance,background:{type:'color',color:'#24282c'}}};
function Lifecycle(){const [index,setIndex]=useState(0),[images,setImages]=useState({}),busy=useRef(false),current=cases[index];window.lifecycle={done:index===cases.length,index,total:cases.length,images,sourceUnchanged:recipes.every(({recipe,before})=>stringifyParticleData(recipe)===before)};
 const ready=async api=>{if(!api||!current||busy.current)return;busy.current=true;try{await api.whenReady();api.fit();const canvas=api.captureFrame({maxDimension:320}),url=canvas.toDataURL('image/png');let f=document.querySelector('#live .game-preview-root');f=f[Object.keys(f).find(k=>k.startsWith('__reactFiber'))];let native;for(;f;f=f.return)for(let h=f.memoizedState;h;h=h.next)if(h.memoizedState?.current?.native)native=h.memoizedState.current.native;if(!native)throw Error('Native runtime missing');const p=native.particlesController.emitters,r=native.ribbonsController.emitters,finite=[...p.flatMap(e=>e.particles.flatMap(p=>[...p.pos,...p.speed,p.lifeSpan])),...r.flatMap(e=>Array.from(e.vertices.slice(0,e.creationTimes.length*6)))].every(Number.isFinite);if(!finite)throw Error('Non-finite native particle or ribbon state');const result={id:current.id,sequence:current.sequence,time:current.time,label:current.label,particles:p.reduce((n,e)=>n+e.particles.length,0),ribbonSegments:r.reduce((n,e)=>n+Math.max(0,e.creationTimes.length-1),0),url};setImages(old=>({...old,[index]:result}));}catch(error){setImages(old=>({...old,[index]:{id:current.id,label:current.label,error:error.message}}));}finally{busy.current=false;setIndex(n=>n+1);}};
 return <><div id="grid">{cases.map((item,i)=><div className="tile" data-index={i} key={i}>{images[i]?.url?<img src={images[i].url}/>:<div style={{height:240}}>{images[i]?.error||'Rendering…'}</div>}<p>{i} · {item.label}</p><p>{images[i]?.particles??'—'} particles · {images[i]?.ribbonSegments??'—'} ribbon segments</p></div>)}</div>{current&&<div id="live"><GamePreview key={index} presentation="preview" model={current.model} textureAssets={current.assets} preferences={prefs} particleAuthoring particleSelectedId={current.model.ParticleEmitters2[0]?.ObjectId??current.model.RibbonEmitters[0]?.ObjectId} sequenceIndex={current.sequence} time={current.time} playing={false} showParticles showGrid={false} mode="textured" view="perspective" onCaptureReady={ready}/></div>}</>;
}
createRoot(document.getElementById('root')).render(<Lifecycle/>);
