// Read-only classic MPQ reader. File-format reference: StormLib SBaseCommon.cpp.
// No legacy 32-bit DLLs are loaded. Unsupported compression is reported, not guessed.
const fs=require('node:fs/promises'),zlib=require('node:zlib');
const crypt=new Uint32Array(1280);let seed=0x100001;
for(let i=0;i<256;i++)for(let j=i;j<1280;j+=256){seed=(seed*125+3)%0x2aaaab;const a=(seed&65535)<<16;seed=(seed*125+3)%0x2aaaab;crypt[j]=(a|(seed&65535))>>>0;}
function hash(name,type){let a=0x7fed7fed,b=0xeeeeeeee;for(const c of Buffer.from(name.replaceAll('/','\\').toUpperCase(),'latin1')){a=(crypt[(type<<8)+c]^(a+b))>>>0;b=(c+a+b+(b<<5)+3)>>>0;}return a;}
function decrypt(input,key){const out=Buffer.from(input);let b=0xeeeeeeee;for(let p=0;p+4<=out.length;p+=4){b=(b+crypt[0x400+(key&255)])>>>0;const v=(out.readUInt32LE(p)^(key+b))>>>0;out.writeUInt32LE(v,p);key=(((~key<<21)+0x11111111)|(key>>>11))>>>0;b=(v+b+(b<<5)+3)>>>0;}return out;}
function unpack(data,expected){if(data.length===expected)return data;if(!data.length)throw Error('Empty compressed MPQ sector.');if(data[0]!==2)throw Error('Unsupported MPQ compression mask '+data[0]);const out=zlib.inflateSync(data.subarray(1),{maxOutputLength:expected});if(out.length!==expected)throw Error('MPQ sector size mismatch.');return out;}
class Mpq {
  static async open(file){const fd=await fs.open(file,'r');try{const stat=await fd.stat();const self=new Mpq(fd,stat.size,file);let base=0;const head=await self.readAt(0,Math.min(4096,stat.size));if(head.toString('binary',0,4)==='MPQ\x1b')base=head.readUInt32LE(8);else if(head.toString('binary',0,4)!=='MPQ\x1a'){base=-1;for(let p=512;p+32<=head.length;p+=512)if(head.toString('binary',p,p+4)==='MPQ\x1a'){base=p;break;}if(base<0)throw Error('MPQ header not found.');}self.base=base;const header=await self.readAt(base,32);if(header.toString('binary',0,4)!=='MPQ\x1a')throw Error('Invalid MPQ header.');if(header.readUInt16LE(12)!==0)throw Error('Only classic MPQ archives are supported.');const shift=header.readUInt16LE(14);if(shift>16)throw Error('Invalid MPQ sector size.');self.sectorSize=512*2**shift;const hc=header.readUInt32LE(24),bc=header.readUInt32LE(28);if(hc>2**22||bc>2**22)throw Error('MPQ index is too large.');self.hashes=decrypt(await self.readAt(base+header.readUInt32LE(16),hc*16),hash('(hash table)',3));self.blocks=decrypt(await self.readAt(base+header.readUInt32LE(20),bc*16),hash('(block table)',3));self.hashCount=hc;return self;}catch(e){await fd.close();throw e;}}
  constructor(fd,size,file){this.fd=fd;this.size=size;this.file=file;}
  async readAt(position,length){if(!Number.isSafeInteger(position)||position<0||length<0||length>128*1024*1024||position+length>this.size)throw Error('MPQ block exceeds archive bounds.');const b=Buffer.alloc(length);let done=0;while(done<length){const {bytesRead}=await this.fd.read(b,done,length-done,position+done);if(!bytesRead)throw Error('Truncated MPQ archive.');done+=bytesRead;}return b;}
  async read(name){const a=hash(name,1),b=hash(name,2),start=hash(name,0)%this.hashCount;let block=-1;for(let n=0;n<this.hashCount;n++){const p=((start+n)%this.hashCount)*16,id=this.hashes.readUInt32LE(p+12);if(id===0xffffffff)break;if(id===0xfffffffe)continue;if(this.hashes.readUInt32LE(p)===a&&this.hashes.readUInt32LE(p+4)===b){block=id;if(this.hashes.readUInt16LE(p+8)===0)break;}}
    if(block<0)return null;const p=block*16;if(p+16>this.blocks.length)throw Error('MPQ hash points outside the block table.');const offset=this.blocks.readUInt32LE(p),packed=this.blocks.readUInt32LE(p+4),size=this.blocks.readUInt32LE(p+8),flags=this.blocks.readUInt32LE(p+12);if(!(flags&0x80000000))return null;if(size>64*1024*1024)throw Error('Texture exceeds64MB.');if(flags&0x100)throw Error('PKWARE-imploded MPQ file is unsupported.');let key=hash(name.split(/[\\/]/).at(-1),3);if(flags&0x20000)key=((key+offset)^size)>>>0;let data=await this.readAt(this.base+offset,packed);const encrypted=!!(flags&0x10000);
    if(!(flags&0x200)&&data.length!==size)throw Error('Uncompressed MPQ file size mismatch.');
    if(flags&0x1000000){if(encrypted)data=decrypt(data,key);return flags&0x200?unpack(data,size):data.subarray(0,size);}
    if(!(flags&0x200)){if(!encrypted)return data.subarray(0,size);const parts=[];for(let i=0,pos=0;pos<size;i++,pos+=this.sectorSize)parts.push(decrypt(data.subarray(pos,Math.min(size,pos+this.sectorSize)),(key+i)>>>0));return Buffer.concat(parts,size);}
    const count=Math.ceil(size/this.sectorSize),tableLength=(count+1)*4;if(data.length<tableLength)throw Error('Truncated MPQ sector table.');const table=encrypted?decrypt(data.subarray(0,tableLength),(key-1)>>>0):data.subarray(0,tableLength);const out=[];for(let i=0;i<count;i++){const from=table.readUInt32LE(i*4),to=table.readUInt32LE(i*4+4);if(from<tableLength||to<from||to>data.length)throw Error('Invalid MPQ sector offset.');let sector=data.subarray(from,to);if(encrypted)sector=decrypt(sector,(key+i)>>>0);out.push(unpack(sector,Math.min(this.sectorSize,size-i*this.sectorSize)));}return Buffer.concat(out,size);
  }
  close(){return this.fd.close();}
}
module.exports={Mpq,hash,decrypt};
