import React,{useState,useEffect,useRef} from 'react';
import {Plus,Trash2,Diamond,ChevronDown} from 'lucide-react';
import {setKey} from '../src/editor-commands.js';
export function TextField({label,value,onChange,type='text',min,max,step='any',disabled=false}){
  const [draft,setDraft]=useState(value??'');const cancel=useRef(false);useEffect(()=>setDraft(value??''),[value]);
  const commit=()=>{if(cancel.current){cancel.current=false;return;}if(disabled)return;const next=type==='number'?Number(draft):draft;if(type==='number'&&(!Number.isFinite(next)||(Number(step)===1&&!Number.isInteger(next))||(min!==undefined&&next<min)||(max!==undefined&&next>max))){setDraft(value??'');return;}if(next!==(value??''))onChange(next);};
  return <label className="field"><span>{label}</span><input data-warmkey={`field:${label}`} data-warmkey-label={`Focus ${label}`} aria-label={label} disabled={disabled} type={type} value={draft} min={min} max={max} step={step} onChange={e=>setDraft(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){cancel.current=true;setDraft(value??'');e.currentTarget.blur();}}}/></label>;
}
export function NumberField(props){return <TextField type="number" {...props}/>;}
export function SelectField({label,value,onChange,options,disabled=false}){return <label className="field"><span>{label}</span><select data-warmkey={`field:${label}`} data-warmkey-label={`Focus ${label}`} aria-label={label} disabled={disabled} value={value??''} onChange={e=>onChange(e.target.value)}>{options.map(o=>typeof o==='string'?<option key={o}>{o}</option>:<option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;}
export function Check({label,value,onChange}){return <label className="check"><input data-warmkey={`toggle:${label}`} data-warmkey-label={`Toggle ${label}`} aria-label={label} type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>;}
export function VectorField({label,value,onChange,size=3,min,max,step='any'}){return <div data-warmkey-prefix={label} className="vector-field"><span>{label}</span><div>{Array.from({length:size},(_,i)=><NumberField key={i} label={['X','Y','Z','W'][i]} value={value?.[i]??0} min={min} max={max} step={step} onChange={v=>{const a=Array.from(value||new Float32Array(size));a[i]=v;onChange(a);}}/>)}</div></div>;}
export function Section({title,children,actions,open=true,warmId}){return <details data-warmkey-prefix={warmId || title} className="inspector-section" open={open}><summary data-warmkey="expand" data-warmkey-label={`Expand or collapse ${warmId || title}`}><ChevronDown size={13}/>{title}<span className="spacer"/>{actions}</summary><div className="section-body">{children}</div></details>;}
export function TrackEditor({label,value,onChange,dimensions=1,frame=0,globalSequences=[],defaultValue=0,integer=false,onlyAnimated=false}){
  const track=value?.Keys?value:null;
  const [expanded,setExpanded]=useState(false);const [keyFrame,setKeyFrame]=useState(Math.round(frame));const [keyValue,setKeyValue]=useState(Array.isArray(defaultValue)?defaultValue.join(', '):String(defaultValue));
  const [error,setError]=useState('');
  const commitTrack=fn=>{const t=structuredClone(track);fn(t);onChange(t);};
  const parse=s=>{const a=s.split(/[\s,]+/).filter(Boolean).map(Number);if(a.length!==dimensions||a.some(n=>!Number.isFinite(n)))throw new Error(`Enter ${dimensions} numeric value${dimensions>1?'s':''}.`);if(integer&&a.some(n=>!Number.isInteger(n)))throw new Error('Values must be integers.');return a;};
  const add=()=>{try{const holder={value:track?structuredClone(track):undefined};setKey(holder,'value',Number(keyFrame),parse(keyValue));onChange(holder.value);setError('');}catch(e){setError(e.message);}};
  return <div data-warmkey-prefix={label} className="track-field"><div className="track-heading"><span>{label}</span>{track?<button data-warmkey="fields:action:1" onClick={()=>setExpanded(!expanded)} className="track-badge"><Diamond size={11}/>{track.Keys.length} keys</button>:<button data-warmkey="fields:action:2" className="subtle tiny" title={'Animate '+label} onClick={()=>{const v=dimensions===1?[Number(value??defaultValue)]:Array.from(value||defaultValue);onChange({LineType:1,Keys:[{Frame:Math.round(frame),Vector:new Float32Array(v)}]});setExpanded(true);}}><Diamond size={12}/>Animate</button>}</div>
  {!track&&!onlyAnimated&&(dimensions===1?<NumberField label="Value" value={typeof value==='number'?value:defaultValue} step={integer?1:'any'} onChange={onChange}/>:<VectorField label="Value" size={dimensions} value={value||defaultValue} onChange={v=>onChange(new Float32Array(v))}/>)}
  {track&&expanded&&<div className="track-editor"><SelectField label="Interpolation" value={track.LineType} options={['Step','Linear','Hermite','Bezier'].map((label,value)=>({label,value}))} onChange={v=>commitTrack(t=>{t.LineType=Number(v);if(t.LineType>=2)for(const k of t.Keys){k.InTan??=new Float32Array(k.Vector);k.OutTan??=new Float32Array(k.Vector);}else for(const k of t.Keys){delete k.InTan;delete k.OutTan;}})}/>
  <SelectField label="Global sequence" value={track.GlobalSeqId??-1} options={[{label:'Local sequence',value:-1},...globalSequences.map((d,i)=>({label:`Global ${i} · ${d} ms`,value:i}))]} onChange={v=>commitTrack(t=>{if(Number(v)<0)delete t.GlobalSeqId;else t.GlobalSeqId=Number(v);})}/>
  <div className="key-list">{track.Keys.map((k,i)=><div data-warmkey-prefix={`key:${k.Frame}`} className="key-row" key={i}><NumberField label="Time" min={0} step={1} value={k.Frame} onChange={v=>{if(track.Keys.some((o,j)=>j!==i&&o.Frame===v)){setError('A key already exists at that time.');return;}commitTrack(t=>{t.Keys[i].Frame=v;t.Keys.sort((a,b)=>a.Frame-b.Frame);});}}/><TextField label="Value" value={Array.from(k.Vector).map(n=>Number(n.toFixed(5))).join(', ')} onChange={v=>{try{const a=parse(v);commitTrack(t=>t.Keys[i].Vector=integer?new Int32Array(a):new Float32Array(a));setError('');}catch(e){setError(e.message);}}}/><button data-warmkey="fields:action:3" className="icon danger" aria-label={'Delete key '+k.Frame} onClick={()=>commitTrack(t=>t.Keys.splice(i,1))}><Trash2 size={12}/></button>{track.LineType>=2&&<div className="tangents">{['InTan','OutTan'].map(p=><TextField key={p} label={p==='InTan'?'In tangent':'Out tangent'} value={Array.from(k[p]||k.Vector).join(', ')} onChange={v=>{try{const a=parse(v);commitTrack(t=>t.Keys[i][p]=new Float32Array(a));setError('');}catch(e){setError(e.message);}}}/>)}</div>}</div>)}</div>
  <div className="new-key"><NumberField label="New time" min={0} step={1} value={keyFrame} onChange={setKeyFrame}/><button data-warmkey="fields:action:4" className="subtle tiny" onClick={()=>setKeyFrame(Math.round(frame))}>Use playhead</button></div><TextField label="New value" value={keyValue} onChange={setKeyValue}/><button data-warmkey="fields:action:5" className="wide subtle" onClick={add}><Plus size={13}/>Set key</button>
  {!onlyAnimated&&<button data-warmkey="fields:action:6" className="subtle tiny" onClick={()=>{const v=track.Keys[0]?.Vector;onChange(dimensions===1?(v?.[0]??0):new Float32Array(v||defaultValue));}}>Convert to static (first key)</button>}
  {error&&<p className="field-error">{error}</p>}</div>}
  </div>;
}
