import React,{useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {usePaintImageNavigation} from './usePaintImageNavigation.js';
import {shapeSelection,combineSelection} from '../src/paint-selection.js';
import {paintMessage as msg} from '../src/paint-messages.js';

/** A texture/UV view of the current paint target. Pixel edits share the 3D
 * painter's coats and history; UV edits are owned by the portable preset.
 */
export default function PaintTextureCanvas({canvas,version,title,geoset,coordId=0,brush,brushPreview,outside=false,textureSmoothing=false,decal,disabled,onStart,onMove,onEnd,onCancel,onHover,onUVChange,regionMask,onGrab,onCopy,onPaste,selectedFaces,onSeparate,onMask}) {
  const display=useRef(),regionCanvas=useRef(),image=useRef(),scroll=useRef(),cursor=useRef(),gesture=useRef(null);
  const [zoomChoice,setZoomChoice]=useState('fit'),[fit,setFit]=useState(1),[mesh,setMesh]=useState(false),[tool,setTool]=useState('paint'),[draft,setDraft]=useState(null),[angle,setAngle]=useState(0),[scale,setScale]=useState(100);
  const width=canvas?.width||256,height=canvas?.height||256,zoom=zoomChoice==='fit'?fit:Number(zoomChoice),uv=draft||geoset?.TVertices?.[coordId];
  const navigation=usePaintImageNavigation(scroll,image,zoom,setZoomChoice,()=>{onEnd();onHover?.(null);});
  const selectedIds=useMemo(()=>selectedFaces?new Set([...selectedFaces].flatMap(face=>[...geoset.Faces.subarray(face*3,face*3+3)])):null,[selectedFaces,geoset]);
  const action=useRef();action.current=id=>{if(id==='mirror'&&tool==='moveUV')transform(true);if(id==='paint')setTool('paint');if(id==='fit')setZoomChoice('fit');if(id==='mesh')setMesh(v=>!v);if(id==='mapping'){setTool(v=>v==='moveUV'?'paint':'moveUV');setMesh(true);}if(id==='select')setTool(v=>v==='pixels'?'paint':'pixels');};
  useEffect(()=>{const fn=e=>action.current(e.detail);window.addEventListener('paint-texture-action',fn);return()=>window.removeEventListener('paint-texture-action',fn);},[]);
  const uvPath=useMemo(()=>uv?Array.from({length:Math.floor((geoset?.Faces.length||0)/3)},(_,i)=>{const ids=Array.from(geoset.Faces.slice(i*3,i*3+3));return ids.map((id,j)=>(j?'L':'M')+uv[id*2]*width+','+uv[id*2+1]*height).join(' ')+'Z';}).join(' '):'', [uv,geoset?.Faces,width,height]);
  const selectedPath=useMemo(()=>selectedFaces&&uv?[...selectedFaces].map(i=>[...geoset.Faces.slice(i*3,i*3+3)].map((id,j)=>(j?'L':'M')+uv[id*2]*width+','+uv[id*2+1]*height).join(' ')+'Z').join(' '):'', [selectedFaces,uv,geoset,width,height]);
  useEffect(()=>{const element=scroll.current,resize=()=>setFit(Math.max(.01,Math.min((element.clientWidth-32)/width,(element.clientHeight-32)/height)));const observer=new ResizeObserver(resize);observer.observe(element);resize();return()=>observer.disconnect();},[width,height]);
  useLayoutEffect(()=>{if(!canvas||!display.current)return;if(display.current.width!==canvas.width)display.current.width=canvas.width;if(display.current.height!==canvas.height)display.current.height=canvas.height;display.current.getContext('2d').clearRect(0,0,canvas.width,canvas.height);display.current.getContext('2d').drawImage(canvas,0,0);},[canvas,version]);
  useEffect(()=>{if(!regionCanvas.current||!regionMask)return;const c=regionCanvas.current;c.width=width;c.height=height;const data=new Uint8ClampedArray(width*height*4);for(let i=0;i<regionMask.length;i++)data.set([5,20,30,Math.round((255-regionMask[i])*.35)],i*4);c.getContext('2d').putImageData(new ImageData(data,width,height),0,0);},[regionMask,width,height]);
  useEffect(()=>{setDraft(null);},[geoset,coordId]);
  const point=e=>{const rect=image.current.getBoundingClientRect();return{x:(e.clientX-rect.left)/zoom,y:(e.clientY-rect.top)/zoom};};
  const hit=e=>({textureView:true,screen:point(e),viewport:{width,height}});
  function down(e){if(e.button!==0||disabled)return;e.preventDefault();image.current.setPointerCapture(e.pointerId);
    if(tool==='pixels'||e.shiftKey||e.ctrlKey){gesture.current={mask:true,before:regionMask,start:point(e),operation:e.ctrlKey?'subtract':e.shiftKey?'add':'replace'};return;}
    if(tool==='moveUV'&&uv){gesture.current={start:point(e),uv:new Float32Array(uv)};return;}
    gesture.current={paint:true};onStart(hit(e));
  }
  function move(e){const p=point(e);if(cursor.current)Object.assign(cursor.current.style,{display:tool==='paint'?'block':'none',left:p.x*zoom+'px',top:p.y*zoom+'px'});
    const drag=gesture.current;if(!drag){if(tool==='paint'&&!disabled)onHover?.(hit(e));return;}if(drag.paint){onMove(hit(e));return;}if(drag.mask){onMask(combineSelection(drag.before||new Uint8ClampedArray(width*height).fill(drag.operation==='subtract'?255:0),shapeSelection(width,height,'rectangle',[drag.start,p]),drag.operation));return;}
    setDraft(Float32Array.from(drag.uv,(value,i)=>value+(!selectedIds||selectedIds.has(Math.floor(i/2))?(i%2?(p.y-drag.start.y)/height:(p.x-drag.start.x)/width):0)));
  }
  function end(e){const drag=gesture.current;if(!drag)return;gesture.current=null;if(drag.paint)onEnd();else if(!drag.mask){const p=point(e),next=Float32Array.from(drag.uv,(value,i)=>value+(!selectedIds||selectedIds.has(Math.floor(i/2))?(i%2?(p.y-drag.start.y)/height:(p.x-drag.start.x)/width):0));onUVChange(next);setDraft(null);}}
  function transform(flip=false){if(!uv)return;const ids=selectedIds?[...selectedIds]:Array.from({length:uv.length/2},(_,i)=>i);if(!ids.length)return;let x=0,y=0;for(const id of ids){x+=uv[id*2];y+=uv[id*2+1];}x/=ids.length;y/=ids.length;const c=Math.cos(angle*Math.PI/180),s=Math.sin(angle*Math.PI/180),next=new Float32Array(uv);for(const id of ids){const i=id*2,dx=(uv[i]-x)*scale/100*(flip?-1:1),dy=(uv[i+1]-y)*scale/100;next[i]=x+dx*c-dy*s;next[i+1]=y+dx*s+dy*c;}onUVChange(next);setAngle(0);setScale(100);}
  return <div className="paint-texture-view" onKeyDown={e=>{if(tool==='moveUV'&&e.key==='Enter'){e.preventDefault();e.stopPropagation();transform();}}}><div className="paint-texture-heading" title={title}>Destination · {title}</div><div className="paint-texture-toolbar"><button aria-label="Adjust mapping" aria-pressed={tool==='moveUV'} onClick={()=>action.current('mapping')}>UVs <kbd className="paint-key">U</kbd></button><button aria-pressed={tool==='pixels'} onClick={()=>action.current('select')}>Pixels <kbd className="paint-key">S</kbd></button><button aria-label="Show UV mesh" aria-pressed={mesh} onClick={()=>setMesh(v=>!v)}>Mesh <kbd className="paint-key">W</kbd></button><button aria-label="Fit texture" onClick={()=>setZoomChoice('fit')}>Fit <kbd className="paint-key">0</kbd></button><small>{Math.round(zoom*100)}% · Wheel zoom · Right-drag pan</small>{onGrab&&<button aria-label="Copy a patch" onClick={onGrab}>Cut patch <kbd className="paint-key">Ctrl+Shift+C</kbd></button>}</div>
    {tool==='moveUV'&&<div className="paint-texture-toolbar"><label>{msg('paint.scale')}<input type="number" min="1" value={scale} onChange={e=>setScale(+e.target.value)}/>%</label><label>{msg('paint.angle')}<input type="number" value={angle} onChange={e=>setAngle(+e.target.value)}/>°</label><button onClick={()=>transform()}>{msg('paint.applyUV')} <kbd className="paint-key" aria-hidden="true">Enter</kbd></button><button onClick={()=>transform(true)}>Mirror UVs <kbd className="paint-key" aria-hidden="true">Shift+M</kbd></button><button disabled={!selectedFaces?.size} onClick={onSeparate}>Separate this part <kbd className="paint-key" aria-hidden="true">Ctrl+J</kbd></button><small>{selectedFaces?'Drag selected faces':'Drag this geoset'} · Enter applies scale / rotation</small></div>}
    <div ref={scroll} className="paint-texture-scroll" {...navigation} onPointerDown={e=>{if(outside&&tool==='paint'&&!image.current.contains(e.target))down(e);}} onPointerMove={e=>{if(outside&&!image.current.contains(e.target))move(e);}} onPointerLeave={()=>{if(cursor.current)cursor.current.style.display='none';}}><div ref={image} className="paint-texture-image" style={{width:width*zoom,height:height*zoom,cursor:tool==='moveUV'?'move':'crosshair'}} onPointerDown={down} onPointerMove={move} onPointerUp={end} onPointerCancel={()=>{gesture.current=null;setDraft(null);onCancel();}} onPointerLeave={()=>{if(cursor.current)cursor.current.style.display='none';onHover?.(null);}}>
      <canvas ref={display} style={{imageRendering:textureSmoothing?'auto':'pixelated'}}/>{mesh&&uv&&<svg viewBox={`0 0 ${width} ${height}`}><path d={uvPath} style={{opacity:selectedFaces?.size?.25:1}}/>{selectedPath&&<path d={selectedPath} style={{stroke: "#ffdc42",strokeWidth:2}}/>}</svg>}
      {regionMask&&<canvas ref={regionCanvas} aria-label="Paint region mask"/>}
      <div ref={cursor} className={'paint-texture-cursor paint-visible-cursor'+(decal?' paint-detail-outline':'')} style={{width:(decal?.width||brush.size)*zoom,height:(decal?.height||brush.size)*zoom,transform:`translate(-50%,-50%) rotate(${decal?.angle||0}deg)`}}>{decal?<img className="paint-stamp-ghost" src={decal.url} style={{transform:decal.flipX?'scaleX(-1)':'none'}}/>:<img src={brushPreview}/>}</div>
    </div></div>
  </div>;
}
