import React,{useEffect,useLayoutEffect,useRef,useState} from 'react';
import {Brush,Stamp,Eraser,Undo2,Redo2,Scissors,BookmarkPlus,Focus,Pipette} from 'lucide-react';
import {PAINT_BRUSH_SHAPES} from '../src/paint-brush-shapes.js';
import {paintRampColor} from '../src/paint-palette.js';
import {paintRegionEntries} from '../src/paint-region.js';

export function PaintKey({children}){return <kbd aria-hidden="true" className="paint-key">{children}</kbd>;}
function Action({label,keys,children,...props}){return <button aria-label={label} title={keys?`${label} (${keys})`:label} {...props}>{children}{label}{keys&&<PaintKey>{keys}</PaintKey>}</button>;}
function Slider({label,value,min=0,max=1,step=.01,onChange,suffix='',keys}){
  return <label className="studio-slider"><span>{label}{keys&&<PaintKey>{keys}</PaintKey>}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/><input aria-label={label+' value'} type="number" min={min} max={max} step={step} value={Number(value.toFixed(2))} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))onChange(Math.max(min,Math.min(max,e.target.valueAsNumber)));}}/><small>{suffix}</small></label>;
}
const swatches=['#d9b451','#9ea9b2','#722a25','#324c70','#5c7950','#653e28','#dfd1a8','#f2f0e8','#262b30'];
const shortcuts=[['B / T / E','Paint / Stamp / Erase'],['D / I','Blend brush / Pick color'],['Q','Toggle selection'],['P / G / F','Connected piece / Geoset / Faces'],['Shift + click / drag','Add to selection in any tool'],['Ctrl + click / drag','Subtract in any tool'],['Ctrl+A / Ctrl+D / Ctrl+I','Select all / Clear / Invert'],['X','Protect texture pixels'],['L / O / Y','Isolate / Outlines / Colorfy'],['H / F6 / Home','Shading / Original / Frame model'],['C','Build related color palette'],['[ / ]','Smaller / larger brush or stamp'],['- / +','Lower / raise opacity'],['Shift+[ / Shift+]','Lower / raise softness or Blend strength'],['Shift+M','Mirror the selected UVs'],['R (hold)','Start outside the edge; selection stays protected'],[', / . / M','Rotate stamp -15 / +15 / mirror'],['1 / 2 / 3','Full image / Texture / Highlights'],['4 / 5 / 6 / 7 / 8','Round / Soft / Pencil / Chisel / Speckle'],['Ctrl+C / Ctrl+V','Copy selection / paste as stamp'],['Ctrl+Shift+C','Cut a patch from the texture'],['Ctrl+X','Copy and erase active paint in selection'],['K / Ctrl+K','Cut source / Keep source'],['U / S / W / 0','Adjust UVs / Select pixels / UV mesh / Fit texture'],['Ctrl+J','Give the active part independent UVs'],['Alt + left drag','Rotate model'],['Wheel / Right drag','Zoom / pan texture views'],['Shift+F','Fill selection'],['Ctrl+Z / Ctrl+Y','Undo / redo'],['Ctrl+S / Ctrl+O / Ctrl+N','Save / Open / New paint project'],['Ctrl+E / Ctrl+Enter','Export / Use paint on model'],['J / Ctrl+Shift+O','WC3 library / Import image'],['?','Show this shortcut guide']];

export default function PaintStudioLayout(p){
  const {project,brush,material,tool}=p,controls=useRef(),keys=useRef(),[help,setHelp]=useState(false);
  const limited=!!p.region||p.targetMode==='geoset'||!!p.textureRegion;
  const selectedParts=paintRegionEntries(p.region),faceCount=selectedParts.reduce((n,[,faces])=>n+faces.size,0);
  useLayoutEffect(()=>{if(controls.current)controls.current.scrollTop=0;},[tool,material?.id]);
  keys.current=e=>{
    if(!project||p.disabled||p.dialog)return;
    if(e.target.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;
    if(help&&e.key!=='Escape'&&e.key!=='?'){if(!['Tab','Enter',' '].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();}return;}
    const k=/^Key[A-Z]$/.test(e.code)?e.code.slice(3).toLowerCase():e.code==='Comma'?',':e.code==='Period'?'.':e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;
    let act;
    if(k==='escape')act=()=>{p.onCancel();setHelp(false);};
    else if(k==='?')act=()=>setHelp(v=>!v);
    else if(ctrl){
      act=({a:p.onSelectAll,c:e.shiftKey?p.onGrab:p.onCopy,v:p.onPaste,x:()=>p.onCopy(true),d:p.onClearSelection,i:p.onInvertSelection,z:()=>p.onHistory(e.shiftKey),y:()=>p.onHistory(true),s:p.onSave,o:e.shiftKey?p.onImport:p.onOpen,n:p.onNew,e:p.onExport,enter:p.onDone,j:p.onSeparate,k:p.onSaveSource})[k];
    }else if(!e.altKey){
      act=({b:()=>p.onTool('paint'),t:()=>p.onTool('stamp'),e:()=>p.onTool('erase'),d:()=>p.onTool('blend'),i:()=>p.onTool('sample'),q:p.onSelectToggle,p:()=>p.onSelectionKind('piece'),g:()=>p.onSelectionKind('geoset'),f:e.shiftKey?p.onFill:()=>p.onSelectionKind('faces'),x:p.onTextureMask,l:()=>limited&&p.onIsolate(!p.isolate),o:p.onOutlines,y:p.onColorfy,h:p.onShading,c:p.onPalette,m:e.shiftKey?()=>p.onTextureAction('mirror'):p.onFlip,r:()=>p.onOutside(true),',':()=>p.onStampAngle((p.stampAngle-15+540)%360-180),'.':()=>p.onStampAngle((p.stampAngle+15+540)%360-180),k:p.onCrop,j:p.onNative,home:p.onFrame,f6:p.onOriginal,s:()=>p.onTextureAction('select'),u:()=>p.onTextureAction('mapping'),w:()=>p.onTextureAction('mesh'),'0':()=>p.onTextureAction('fit'),'[':()=>p.onBrush({size:Math.max(1,Math.round(brush.size*.8))}),']':()=>p.onBrush({size:Math.min(1024,Math.max(brush.size+1,Math.round(brush.size*1.25)))}),'-':()=>p.onBrush({opacity:Math.max(0,brush.opacity-.1)}),'=':()=>p.onBrush({opacity:Math.min(1,brush.opacity+.1)}),'+':()=>p.onBrush({opacity:Math.min(1,brush.opacity+.1)})})[k];
      if(e.shiftKey&&(['BracketLeft','BracketRight'].includes(e.code)||['[',']','{','}'].includes(k))){const increase=e.code==='BracketRight'||k===']'||k==='}';act=()=>p.onBrush(tool==='blend'?{blendStrength:Math.max(0,Math.min(1,(brush.blendStrength??.15)+(increase?.05:-.05)))}:{hardness:Math.max(0,Math.min(1,brush.hardness+(increase?-.05:.05)))});}
      if(['1','2','3'].includes(k))act=()=>p.onBorrowMode(['image','texture','highlights'][+k-1]);
      if(['4','5','6','7','8'].includes(k))act=()=>p.onShape(PAINT_BRUSH_SHAPES[+k-4].id);
    }
    if(act){e.preventDefault();e.stopImmediatePropagation();act();}
  };
  const outsideAction=useRef();outsideAction.current=p.onOutside;
  useEffect(()=>{const release=e=>{if(!e||e.code==='KeyR'||e.key?.toLowerCase()==='r')outsideAction.current(false);};window.addEventListener('keyup',release,true);window.addEventListener('blur',release);return()=>{window.removeEventListener('keyup',release,true);window.removeEventListener('blur',release);};},[]);
  useEffect(()=>{if(p.dialog||help||p.disabled)p.onOutside(false);},[p.dialog,help,p.disabled]);
  useEffect(()=>{const listener=e=>keys.current(e),delegate=e=>{keys.current(e.detail);if(e.detail.defaultPrevented)e.preventDefault();};window.addEventListener('keydown',listener,true);window.addEventListener('mdlxl-paint-key',delegate);return()=>{window.removeEventListener('keydown',listener,true);window.removeEventListener('mdlxl-paint-key',delegate);};},[]);
  return <div className={'paint-workspace paint-studio'+(!project?' paint-setup':'')} style={p.style}>
    {project&&<>
      <header className="paint-toolbar studio-toolbar"><strong>Paint</strong><div className="studio-tools" role="group" aria-label="Painting tools">
        {[['paint','Paint','B',Brush],['stamp','Stamp','T',Stamp],['erase','Erase','E',Eraser]].map(([id,label,key,Icon])=><Action key={id} label={label} keys={key} aria-pressed={id==='paint'?['paint','blend','sample'].includes(tool):tool===id} disabled={p.disabled} onClick={()=>p.onTool(id)}><Icon size={15}/></Action>)}
      </div><span className="paint-toolbar-spacer"/>
      <Action label="Shade" keys="H" aria-pressed={p.shading} onClick={p.onShading}/><Action label="Outlines" keys="O" aria-pressed={p.outlines} onClick={p.onOutlines}/><Action label="Colorfy" keys="Y" aria-pressed={p.colorfy} onClick={p.onColorfy}/><Action label="Original" keys="F6" aria-pressed={p.original} onClick={p.onOriginal}/><button title="Frame model (Home)" aria-label="Frame model" onClick={p.onFrame}><Focus size={15}/><PaintKey>Home</PaintKey></button><Action label="Help" keys="?" onClick={()=>setHelp(v=>!v)}/>
      </header>
      <aside ref={controls} className="paint-panel paint-left studio-controls"><fieldset disabled={p.disabled}>
        <section className="studio-selection">
          <div className="studio-section-title"><strong>Where to work</strong><Action label="Select" keys="Q" aria-pressed={p.selecting} onClick={p.onSelectToggle}/></div>
          <div className="studio-segments">{[['piece','Part','P'],['geoset','Geoset','G'],['faces','Faces','F']].map(([id,label,key])=><Action key={id} label={label} keys={key} aria-pressed={p.selectionKind===id} onClick={()=>p.onSelectionKind(id)}/>)}</div>
          <small><PaintKey>Shift</PaintKey> add · <PaintKey>Ctrl</PaintKey> subtract</small>
          {limited?<><span className="studio-selection-count">{p.region?`${faceCount} face${faceCount===1?'':'s'} · ${selectedParts.length} geoset${selectedParts.length===1?'':'s'}`:p.textureRegion?'Texture selection':`Geoset ${p.activeGeoset+1}`}</span><div className="studio-segments"><Action label="Isolate" keys="L" aria-pressed={p.isolate} onClick={()=>p.onIsolate(!p.isolate)}/><Action label="Clear selection" keys="Ctrl+D" onClick={p.onClearSelection}/></div><Action label="Invert selection" keys="Ctrl+I" onClick={p.onInvertSelection}/></>:<small>Whole model</small>}
          <Action label="Protect pixels" keys="X" onClick={p.onTextureMask}/><small className={p.outside?'studio-outside-active':''}><PaintKey>R</PaintKey>{p.outside?'Outside-edge painting active':'Hold to paint from outside the edge'}</small>
        </section>
        {tool==='stamp'?<>
          <section>{material?<><img className="studio-source" src={material.preview} alt={material.name}/><strong className="studio-source-name">{material.name.split(/[\\/]/).at(-1)}</strong><div className="studio-segments"><Action label="Cut out" keys="K" onClick={p.onCrop}><Scissors size={13}/></Action><Action label="Keep" keys="Ctrl+K" onClick={p.onSaveSource}><BookmarkPlus size={13}/></Action></div></>:<small>Choose an image from the shelf.</small>}
            <div className="studio-borrow" role="group" aria-label="Borrow">{[['image','Full image','1'],['texture','Texture','2'],['highlights','Highlights','3']].map(([id,label,key])=><Action key={id} label={label} keys={key} aria-pressed={p.borrowMode===id} onClick={()=>p.onBorrowMode(id)}/>)}</div>
          </section>
        </>:<>
          <section><div className="studio-segments"><Action label="Color" keys="B" aria-pressed={tool==='paint'} onClick={()=>p.onTool('paint')}/><Action label="Blend" keys="D" aria-pressed={tool==='blend'} onClick={()=>p.onTool('blend')}/><button title="Pick color (I)" aria-label="Pick color from model" aria-pressed={tool==='sample'} onClick={()=>p.onTool('sample')}><Pipette size={14}/><PaintKey>I</PaintKey></button></div>
            <label className="paint-color">Color<input aria-label="Paint color" type="color" value={brush.color} onChange={e=>p.onBrush({color:e.target.value})}/></label>
            <div className="studio-swatches">{swatches.map(color=><button key={color} aria-label={'Color '+color} style={{background:color}} onClick={()=>p.onBrush({color})}/>)}</div>
            <Action label="Related colors" keys="C" onClick={p.onPalette}/>
            {p.palette&&<><div className="studio-ramp" role="group" aria-label="Related color palette">{p.palette.map((color,i)=><button key={i} aria-label={`Related shade ${i+1}: ${color}`} title={color} style={{background:color}} onClick={()=>p.onBrush({color})}/>)}</div><input key={p.palette[4]} aria-label="Color gradient" className="studio-gradient" type="range" min="0" max="1000" defaultValue="500" style={{background:`linear-gradient(to right,${p.palette.join(',')})`}} onChange={e=>p.onBrush({color:paintRampColor(p.palette,+e.target.value/1000)})}/><small>Shadow · midtone · highlight</small></>}
          </section>
          <section><div className="studio-brushes" role="group" aria-label="Brush shapes">{PAINT_BRUSH_SHAPES.map((shape,i)=><button key={shape.id} aria-label={shape.name+' brush'} title={shape.name+' ('+(i+4)+')'} aria-pressed={p.shape===shape.id} onClick={()=>p.onShape(shape.id)}><span className={'studio-tip studio-tip-'+shape.id}/><span>{shape.name}</span><PaintKey>{i+4}</PaintKey></button>)}</div></section>
        </>}
        <section><Slider label={tool==='stamp'?'Stamp size':'Brush size'} value={brush.size} min={1} max={1024} step={1} suffix="px" keys="[ ]" onChange={size=>p.onBrush({size})}/><Slider label="Opacity" value={Math.round(brush.opacity*100)} max={100} step={1} suffix="%" keys="− +" onChange={value=>p.onBrush({opacity:value/100})}/>
          {tool==='stamp'?<><Slider label="Rotation" value={p.stampAngle} min={-180} max={180} step={1} suffix="°" keys=", ." onChange={p.onStampAngle}/><Action label="Mirror" keys="M" aria-pressed={p.stampFlip} onClick={p.onFlip}/></>:tool==='blend'?<Slider label="Blend strength" keys="Shift+[ ]" value={Math.round((brush.blendStrength??.15)*100)} max={100} step={1} suffix="%" onChange={value=>p.onBrush({blendStrength:value/100})}/>:<Slider label="Softness" keys="Shift+[ ]" value={Math.round((1-brush.hardness)*100)} max={100} step={1} suffix="%" onChange={value=>p.onBrush({hardness:1-value/100})}/>}
        </section>
        <section className="studio-reuse"><div className="studio-segments"><Action label="Copy" keys="Ctrl+C" onClick={()=>p.onCopy()}/><Action label="Paste" keys="Ctrl+V" disabled={!p.canPaste} onClick={p.onPaste}/></div>{limited&&<Action label="Fill selection with color" keys="Shift+F" onClick={p.onFill}/>}<Action label="Separate this part" keys="Ctrl+J" title="Give the active part its own texture pixels so shared faces stop changing together (Ctrl+J)" disabled={!p.region?.faces.size&&p.targetMode!=='geoset'} onClick={p.onSeparate}/></section>
        <details><summary>Layers & texture</summary><label>Texture<select aria-label="Destination texture" value={project.activeTargetId} onChange={e=>p.onTarget(e.target.value)}>{project.targets.map(t=><option key={t.id} value={t.id}>{t.paintName||t.label}</option>)}</select></label><label>Paint layer<select aria-label="Paint layer" value={project.activeCoatId} onChange={e=>p.onCoat(e.target.value)}>{p.coats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="paint-check"><input type="checkbox" checked={p.coat?.visible!==false} onChange={e=>p.onCoatVisible(e.target.checked)}/>Show layer</label><button onClick={p.onSurface}>Resize texture…</button></details>
      </fieldset></aside>
    </>}
    <section className={'paint-stage'+(project?' paint-stage-split':'')} style={{'--paint-split':p.split+'%'}}><div className="paint-model-view">{p.viewport}</div>
      {project?<><div className="paint-view-divider" role="separator" aria-label="Resize paint views" aria-orientation="horizontal" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();p.onSplit(p.split+(e.key==='ArrowUp'?-5:5));}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.buttons===1){const rect=e.currentTarget.parentElement.getBoundingClientRect();p.onSplit((e.clientY-rect.top)/rect.height*100);}}}/>{p.texture}<div className="paint-stage-label">{p.outside?'Outside edge · selection stays protected':p.original?'Original skin':p.selecting?'Select parts · Q returns to brush':p.colorfy?'Colorfy · view only':limited?'Selection protects the rest':'Whole model'}</div><div className="paint-orbit-hint">{p.navigationHint}</div></>:<section className="paint-start-card"><h2>Citadel Paint</h2><p>Paint your model, borrow Warcraft textures, and mix them together.</p><div className="paint-start-options"><button aria-pressed={p.sourceMode==='current'} onClick={()=>p.onSourceMode('current')}><strong>Edit the texture</strong><span>Start with the skin already on your model.</span></button><button aria-pressed={p.sourceMode==='primer'} onClick={()=>p.onSourceMode('primer')}><strong>New base coat</strong><span>Start with a clean surface and paint your own.</span></button></div>{p.sourceMode==='primer'&&<label className="paint-color">Base coat color<input aria-label="Base coat color" type="color" value={brush.color} onChange={e=>p.onBrush({color:e.target.value})}/></label>}{p.sourceMode==='primer'&&<label className="paint-resolution">Texture size<select value={p.resolution} onChange={e=>p.onResolution(+e.target.value)}><option value="256">256 × 256</option><option value="512">512 × 512</option></select></label>}{p.sourceMode==='current'&&<details className="studio-start-detail"><summary>Texture detail</summary><label>Working size<select aria-label="Working size" value={p.resolution} onChange={e=>p.onResolution(+e.target.value)}><option value="512">512 px · Standard</option><option value="1024">1024 px · Fine detail</option><option value="0">Native · Exact pixel work</option></select></label><small>The skin keeps its layout. Only your working copy changes.</small></details>}<div className="paint-button-row"><button onClick={p.onOpen}>Open project…</button><button className="studio-primary" disabled={p.disabled} onClick={p.onBegin}>{p.busy?'Preparing…':'Begin painting'}</button></div></section>}
    </section>
    {project&&<><aside className="paint-panel paint-right"><fieldset disabled={p.disabled}>{p.shelf}</fieldset></aside><footer className="paint-footer"><button title="Undo (Ctrl+Z)" aria-label="Undo paint" disabled={!project.history.undo.length||p.disabled} onClick={()=>p.onHistory(false)}><Undo2 size={16}/><PaintKey>Ctrl+Z</PaintKey></button><button title="Redo (Ctrl+Y)" aria-label="Redo paint" disabled={!project.history.redo.length||p.disabled} onClick={()=>p.onHistory(true)}><Redo2 size={16}/><PaintKey>Ctrl+Y</PaintKey></button><span role="status">{p.textureName} · {p.width} × {p.height}{project.dirty?' · Unsaved':''}</span><Action label="New…" keys="Ctrl+N" onClick={p.onNew}/><Action label="Open…" keys="Ctrl+O" onClick={p.onOpen}/><Action label="Save project" keys="Ctrl+S" disabled={p.disabled} onClick={p.onSave}/><Action label="Export…" keys="Ctrl+E" disabled={p.disabled} onClick={p.onExport}/><Action label="Use paint on model" keys="Ctrl+↵" className="studio-primary" disabled={p.disabled} onClick={p.onDone}/></footer></>}
    {help&&<div className="paint-modal-shade"><section className="paint-shortcuts" role="dialog" aria-modal="true" aria-label="Paint shortcuts"><header><strong>Paint shortcuts</strong><button autoFocus onClick={()=>setHelp(false)}>Close <PaintKey>Esc</PaintKey></button></header><div>{shortcuts.map(([key,text])=><p key={key}><PaintKey>{key}</PaintKey><span>{text}</span></p>)}</div></section></div>}
    {p.children}
  </div>;
}
