import React,{useLayoutEffect,useRef} from 'react';
import {Brush,Stamp,Blend,Eraser,MousePointer2,Undo2,Redo2,Scissors,BookmarkPlus,Check,X,Focus,Eye,Pipette} from 'lucide-react';

function Slider({label,value,min=0,max=1,step=.01,onChange,suffix=''}){
  return <label className="studio-slider"><span>{label}</span><input aria-label={label} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(+e.target.value)}/><input aria-label={label+' value'} type="number" min={min} max={max} step={step} value={Number(value.toFixed(2))} onChange={e=>{if(Number.isFinite(e.target.valueAsNumber))onChange(Math.max(min,Math.min(max,e.target.valueAsNumber)));}}/><small>{suffix}</small></label>;
}
const tools=[['paint','Paint',Brush],['stamp','Stamp',Stamp],['blend','Blend',Blend],['erase','Erase',Eraser],['select','Select',MousePointer2]];
const swatches=['#d9b451','#9ea9b2','#722a25','#324c70','#5c7950','#653e28','#dfd1a8','#f2f0e8','#262b30'];

/** The visible editor is organized around making marks, placing imagery and
 * selecting the surface. Persistence and projection remain in the workspace. */
export default function PaintStudioLayout(p){
  const {project,brush,material,tool}=p;
  const controls=useRef();
  useLayoutEffect(()=>{if(controls.current)controls.current.scrollTop=0;},[tool,material?.id]);
  const limited=p.region||p.targetMode==='geoset'||p.textureRegion;
  return <div className={'paint-workspace paint-studio'+(!project?' paint-setup':'')} style={p.style} onKeyDownCapture={e=>{
    if(p.dialog||e.target.tagName==='TEXTAREA'||e.target.tagName==='SELECT'||e.target.tagName==='INPUT'&&!/number|range/.test(e.target.type))return;
    if(e.key==='Escape'){p.onCancel();e.preventDefault();e.stopPropagation();}
    if(e.key==='Enter'&&p.placing){p.onCommit();e.preventDefault();e.stopPropagation();}
  }}>
    {project&&<>
      <header className="paint-toolbar studio-toolbar"><strong>Citadel Paint</strong><div className="studio-tools" role="group" aria-label="Painting tools">{tools.map(([id,label,Icon])=><button key={id} aria-pressed={tool===id} disabled={p.disabled} onClick={()=>p.onTool(id)}><Icon size={16}/>{label}</button>)}</div><span className="paint-toolbar-spacer"/><button title="Frame model" aria-label="Frame model" onClick={p.onFrame}><Focus size={16}/></button><button aria-pressed={p.original} onClick={p.onOriginal}><Eye size={16}/>Original</button></header>
      <aside ref={controls} className="paint-panel paint-left studio-controls"><fieldset disabled={p.disabled}>
        <section className="studio-tool-intro"><h3>{tool==='stamp'?'Place an image':tool==='blend'?'Blend your brushwork':tool==='erase'?'Erase paint':tool==='sample'?'Pick a color':tool==='select'?'Choose where to work':'Paint with color'}</h3><p className="paint-help">{tool==='stamp'?'Choose a texture. Click or drag on the model to preview it.':tool==='blend'?'Drag through colors to soften edges and pull them together.':tool==='erase'?'Remove marks from the active layer. The skin underneath stays intact.':tool==='sample'?'Click the model or texture to pick up its color.':tool==='select'?'Pick a part without taking the model apart.':'Paint on the model or its texture below.'}</p></section>
        {tool==='select'?<section><div className="studio-choices">{[['piece','Connected piece'],['geoset','Whole geoset'],['faces','Brush faces']].map(([id,label])=><button key={id} aria-pressed={p.selectionKind===id} onClick={()=>p.onSelectionKind(id)}>{label}</button>)}</div><p className="paint-help">{p.selectionKind==='faces'?'Drag across faces to include them. Shift-drag removes faces.':'Click the piece you want to work on.'}</p><button className="studio-primary" disabled={!limited} onClick={()=>p.onTool(material?'stamp':'paint')}>Use selection</button><button onClick={p.onTextureMask}>Select on texture…</button></section>:<>
          {tool==='paint'&&<section><label className="paint-color">Color<input aria-label="Paint color" type="color" value={brush.color} onChange={e=>p.onBrush({color:e.target.value})}/></label><button onClick={()=>p.onTool('sample')}><Pipette size={14}/>Pick color from model</button><div className="studio-swatches">{swatches.map(color=><button key={color} aria-label={'Color '+color} style={{background:color}} onClick={()=>p.onBrush({color})}/>)}</div></section>}
          {tool==='stamp'&&<section>{material?<><img className="studio-source" src={material.preview} alt={material.name}/><strong className="studio-source-name">{material.name.split(/[\\/]/).at(-1)}</strong><div className="paint-button-row"><button onClick={p.onCrop}><Scissors size={14}/>Cut out</button><button onClick={p.onSaveSource}><BookmarkPlus size={14}/>Keep</button></div></>:<p>Choose an image from the shelf →</p>}<label>Borrow<select aria-label="Borrow" value={p.borrowMode} onChange={e=>p.onBorrowMode(e.target.value)}><option value="image">Full image</option><option value="texture">Texture only</option><option value="highlights">Highlights only</option></select></label><p className="paint-help">{p.borrowMode==='texture'?'Keeps your painted color; borrows the light and dark detail.':p.borrowMode==='highlights'?'Adds the bright detail to the colors already there.':'Places the colors and details of the source image.'}</p></section>}
          <section><Slider label={tool==='stamp'?'Stamp size':'Brush size'} value={brush.size} min={1} max={1024} step={1} suffix="px" onChange={size=>p.onBrush({size})}/><Slider label="Opacity" value={Math.round(brush.opacity*100)} max={100} step={1} suffix="%" onChange={value=>p.onBrush({opacity:value/100})}/>{tool==='stamp'?<><Slider label="Rotation" value={p.stampAngle} min={-180} max={180} step={1} suffix="°" onChange={p.onStampAngle}/><button aria-pressed={p.stampFlip} onClick={p.onFlip}>Flip horizontally</button></>:tool!=='blend'&&<Slider label="Softness" value={Math.round((1-brush.hardness)*100)} max={100} step={1} suffix="%" onChange={value=>p.onBrush({hardness:1-value/100})}/>}</section>
          {tool==='stamp'&&<section className={'studio-placement'+(p.placing?' is-placing':'')}><strong>{p.placing?'Adjust your preview':'Ready to place'}</strong><small>{p.placing?'Drag on the model to move it. Enter applies; Esc cancels.':'The image stays adjustable until you apply it.'}</small></section>}
        </>}
        <section className="studio-selection"><h3>{limited?'Working inside selection':'Working on the whole model'}</h3>{limited&&<><span>{p.region?`${p.region.faces.size} faces · Geoset ${p.activeGeoset+1}`:p.textureRegion?'Texture selection':`Geoset ${p.activeGeoset+1}`}</span><label className="paint-check"><input type="checkbox" checked={p.isolate} onChange={e=>p.onIsolate(e.target.checked)}/>Only show selection</label><button onClick={p.onClearSelection}>Clear selection</button>{!p.textureRegion&&<details><summary>Shared texture pixels</summary><p className="paint-help">Mirrored or overlapping areas share paint. Give this selection its own copy when you want only this piece to change. Compressed areas also get more room for detail.</p><button onClick={p.onSeparate}>Make selection independent</button></details>}</>}{tool!=='select'&&<button onClick={()=>p.onTool('select')}>{limited?'Change selection':'Select a part…'}</button>}{limited&&tool==='paint'&&<button onClick={p.onFill}>Fill selection with color</button>}</section>
        <details><summary>Layers & texture</summary><label>Texture<select aria-label="Destination texture" value={project.activeTargetId} onChange={e=>p.onTarget(e.target.value)}>{project.targets.map(t=><option key={t.id} value={t.id}>{t.paintName||t.label}</option>)}</select></label><label>Paint layer<select aria-label="Paint layer" value={project.activeCoatId} onChange={e=>p.onCoat(e.target.value)}>{p.coats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="paint-check"><input type="checkbox" checked={p.coat?.visible!==false} onChange={e=>p.onCoatVisible(e.target.checked)}/>Show layer</label><button onClick={p.onSurface}>Resize texture…</button></details>
      </fieldset></aside>
    </>}
    <section className={'paint-stage'+(project?' paint-stage-split':'')} style={{'--paint-split':p.split+'%'}}><div className="paint-model-view">{p.viewport}</div>
      {project?<><div className="paint-view-divider" role="separator" aria-label="Resize paint views" aria-orientation="horizontal" tabIndex={0} onKeyDown={e=>{if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();p.onSplit(p.split+(e.key==='ArrowUp'?-5:5));}}} onPointerDown={e=>e.currentTarget.setPointerCapture(e.pointerId)} onPointerMove={e=>{if(e.buttons===1){const rect=e.currentTarget.parentElement.getBoundingClientRect();p.onSplit((e.clientY-rect.top)/rect.height*100);}}}/>{p.texture}{p.placing&&<div className="studio-stamp-actions"><button className="studio-primary" onClick={p.onCommit}><Check size={15}/>Apply stamp</button><button onClick={p.onCancel}><X size={15}/>Cancel</button><small>Enter / Esc</small></div>}<div className="paint-stage-label">{p.original?'Original skin':tool==='select'?'Choose a piece on the model':p.placing?'Stamp preview · Apply when ready':limited?'Painting selected area':'Paint anywhere'}</div><div className="paint-orbit-hint">{p.navigationHint}</div></>:<section className="paint-start-card"><h2>Make it yours.</h2><p>Paint your model, borrow Warcraft textures, and mix them together.</p><div className="paint-start-options"><button aria-pressed={p.sourceMode==='current'} onClick={()=>p.onSourceMode('current')}><strong>Edit the texture</strong><span>Start with the skin already on your model.</span></button><button aria-pressed={p.sourceMode==='primer'} onClick={()=>p.onSourceMode('primer')}><strong>New base coat</strong><span>Start with a clean surface and paint your own.</span></button></div>{p.sourceMode==='primer'&&<label className="paint-color">Base coat color<input aria-label="Base coat color" type="color" value={brush.color} onChange={e=>p.onBrush({color:e.target.value})}/></label>}{p.sourceMode==='primer'&&<label className="paint-resolution">Texture size<select value={p.resolution} onChange={e=>p.onResolution(+e.target.value)}><option value="256">256 × 256</option><option value="512">512 × 512</option></select></label>}{p.sourceMode==='current'&&<details className="studio-start-detail"><summary>Texture detail</summary><label>Working size<select aria-label="Working size" value={p.resolution} onChange={e=>p.onResolution(+e.target.value)}><option value="512">512 px · Standard</option><option value="1024">1024 px · Fine detail</option><option value="0">Native · Exact pixel work</option></select></label><small>The skin keeps its layout. Only your working copy changes.</small></details>}<div className="paint-button-row"><button onClick={p.onOpen}>Open project…</button><button className="studio-primary" disabled={p.disabled} onClick={p.onBegin}>{p.busy?'Preparing…':'Begin painting'}</button></div></section>}
    </section>
    {project&&<><aside className="paint-panel paint-right"><fieldset disabled={p.disabled}>{p.shelf}</fieldset></aside><footer className="paint-footer"><button title="Undo" aria-label="Undo paint" disabled={!project.history.undo.length||p.disabled} onClick={()=>p.onHistory(false)}><Undo2 size={16}/></button><button title="Redo" aria-label="Redo paint" disabled={!project.history.redo.length||p.disabled} onClick={()=>p.onHistory(true)}><Redo2 size={16}/></button><span role="status">{p.textureName} · {p.width} × {p.height}{project.dirty?' · Unsaved':''}</span><button onClick={p.onNew}>New…</button><button onClick={p.onOpen}>Open…</button><button disabled={p.disabled} onClick={p.onSave}>Save project</button><button disabled={p.disabled} onClick={p.onExport}>Export…</button><button className="studio-primary" disabled={p.disabled} onClick={p.onDone}>Use paint on model</button></footer></>}
    {p.children}
  </div>;
}
