import React,{Suspense,lazy,useCallback,useMemo,useRef,useState} from 'react';
import {particleInspectionModel,particleConstantRateEstimate} from '../src/particle-inspection.js';
const GamePreview=lazy(()=>import('./GamePreview.jsx'));
export default function ParticleTestView({source,ids,assets,preferences,sequence,frame,onClose}){
 const [instances,setInstances]=useState(1),[distance,setDistance]=useState(300),[dark,setDark]=useState(true),[team,setTeam]=useState('#ed3333'),[playing,setPlaying]=useState(true),[time,setTime]=useState(frame),[clip,setClip]=useState(sequence),[status,setStatus]=useState({}),[error,setError]=useState(''),[cost,setCost]=useState(false),capture=useRef(null);
 const inspection=useMemo(()=>{try{return {model:particleInspectionModel(source,ids,{instances})};}catch(e){return {error:e.message};}},[source,ids,instances]),model=inspection.model;
 const prefs=useMemo(()=>({...preferences,viewportAppearance:{...preferences.viewportAppearance,background:{type:'color',color:dark?'#24282c':'#d0d0d0'}}}),[preferences,dark]);
 const ready=useCallback(async api=>{capture.current=api;if(!api)return;try{await api.whenReady();if(capture.current!==api)return;api.fit();const view=api.cameraView(),offset=view.position.map((v,i)=>v-view.target[i]),length=Math.hypot(...offset)||1;api.setCameraView({...view,position:view.target.map((v,i)=>v+offset[i]/length*distance)});setError('');}catch(e){setError(e.message);}},[distance]);
 const report=useCallback(next=>setStatus(old=>cost||old.error!==next.error||old.busy!==next.busy?next:old),[cost]);
 const estimate=particleConstantRateEstimate(model||{}),range=model?.Sequences[clip]?.Interval||[0,5000];
 return <div className="pe-test-view" role="dialog" aria-label="Effect test view" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}}}><header><strong>Effect test view</strong><button onClick={onClose}>Close test view</button></header><div className="pe-test-options"><label>Instances<select aria-label="Test instances" value={instances} onChange={e=>setInstances(Number(e.target.value))}>{[1,4,9].map(n=><option key={n}>{n}</option>)}</select></label><label>Distance<select aria-label="Test distance" value={distance} onChange={e=>setDistance(Number(e.target.value))}><option value={300}>Close</option><option value={900}>Game-like</option><option value={1800}>Far</option></select></label><label>Team color<select aria-label="Test team color" value={team} onChange={e=>setTeam(e.target.value)}><option value="#ed3333">Red</option><option value="#0042ff">Blue</option></select></label><button onClick={()=>setDark(v=>!v)}>{dark?'Light background':'Dark background'}</button></div>{model&&<><div className="pe-test-stage"><Suspense fallback={<span>Loading preview…</span>}><GamePreview key={instances} presentation="preview" model={model} textureAssets={assets} preferences={prefs} teamColor={team} particleAuthoring onParticleStatus={report} sequenceIndex={clip} time={time} playing={playing} onTimeChange={setTime} onPlayingChange={setPlaying} onCaptureReady={ready} showParticles showGrid={false} mode="textured" view="perspective"/></Suspense></div><div className="pe-transport"><button onClick={()=>setPlaying(v=>!v)}>{playing?'Pause test':'Play test'}</button><input aria-label="Test playhead" type="range" min={range[0]} max={range[1]} value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><select aria-label="Test animation" value={clip} onChange={e=>{const i=Number(e.target.value);setClip(i);setTime(model.Sequences[i].Interval[0]);}}>{model.Sequences.map((s,i)=><option key={i} value={i}>{s.Name}</option>)}</select></div></>}{(inspection.error||error||status.error)&&<p role="status">{inspection.error||error||status.error}</p>}<details onToggle={e=>setCost(e.currentTarget.open)}><summary>Preview cost</summary>{cost&&<div><p>{status.liveParticles??0} live sprites/streaks · {status.liveRibbons??0} ribbon segments</p>{estimate!==null&&<p>Constant-rate estimate: about {Math.round(estimate)} live particles at steady state.</p>}<small>Distance and repeated instances are preview settings. Actual game cost still needs Warcraft testing.</small></div>}</details></div>;
}
