import React,{useEffect,useRef,useState} from 'react';
import {particleFrameGroups,particleBlendNames,particleGridChange,particleCellAt} from '../src/particle-picture.js';
import {particlePictureCanvas} from './particle-picture-canvas.js';
import {ParticleSlider} from './ParticleCluelessControls.jsx';
import ParticleBlendComparisons from './ParticleBlendComparisons.jsx';
const key=path=>String(path||'').replaceAll('/','\\').toLowerCase();
function PictureTile({asset,replaceableId,teamColor,label,selected,onClick}){
 const canvas=useRef(null),[missing,setMissing]=useState(false);
 useEffect(()=>{let live=true;setMissing(false);particlePictureCanvas(asset,{replaceableId,teamColor}).then(image=>{if(live){const c=canvas.current.getContext('2d');c.clearRect(0,0,64,64);c.drawImage(image,0,0,64,64);}}).catch(()=>{if(live)setMissing(true);});return()=>{live=false;};},[asset,replaceableId,teamColor]);
 return <button className="pe-picture-tile" onClick={onClick} aria-pressed={selected} aria-label={label}><canvas ref={canvas} width="64" height="64"/><span>{missing?'Missing picture':label}</span></button>;
}
export default function ParticlePictureTool({model,emitter,assets,asset,preferences,teamColor,sequence,frame,update,patch,onImport,onTeamPicture,onDemo,demo,begin,change,finish,cancel}){
 const canvas=useRef(null),[group,setGroup]=useState('LifeSpanUVAnim'),[endpoint,setEndpoint]=useState(0),[pending,setPending]=useState(null),[message,setMessage]=useState(''),[compare,setCompare]=useState(null),[pictureLimit,setPictureLimit]=useState(64);
 const replaceableId=emitter.ReplaceableId||model.Textures[emitter.TextureID]?.ReplaceableId||0;
 const rows=emitter.Rows,columns=emitter.Columns,values=emitter[group]||[0,0,1],visibleGrid=rows*columns<=4096&&rows<=256&&columns<=256;
 useEffect(()=>{let live=true;const target=canvas.current;if(!target)return;const c=target.getContext('2d');c.clearRect(0,0,256,256);
 particlePictureCanvas(asset,{replaceableId,teamColor}).then(image=>{if(!live)return;setMessage('');c.drawImage(image,0,0,256,256);if(visibleGrid){c.strokeStyle='#a7dfff';c.lineWidth=.7;for(let x=0;x<=columns;x++){c.beginPath();c.moveTo(x*256/columns,0);c.lineTo(x*256/columns,256);c.stroke();}for(let y=0;y<=rows;y++){c.beginPath();c.moveTo(0,y*256/rows);c.lineTo(256,y*256/rows);c.stroke();}c.lineWidth=3;c.strokeStyle='#ffce5a';for(const cell of [values[0],values[1]>values[0]?values[1]-1:values[1]])c.strokeRect(cell%columns*256/columns,Math.floor(cell/columns)*256/rows,256/columns,256/rows);}}).catch(()=>{if(live)setMessage('Resolve this picture to edit its visible cells.');});return()=>{live=false;};},[asset,replaceableId,teamColor,rows,columns,values[0],values[1],visibleGrid]);
 const grid=(r,c)=>{try{const result=particleGridChange(emitter,r,c);if(result.invalid.length)setPending({rows:r,columns:c,...result});else{patch(result.values);setPending(null);}}catch(error){setMessage(error.message);}};
 return <div className="pe-picture-tool">
  <details><summary>Choose picture</summary><div className="pe-picture-choices">{model.Textures.slice(0,pictureLimit).map((t,i)=><PictureTile key={i} asset={assets.get(key(t.Image))} replaceableId={t.ReplaceableId} teamColor={teamColor} label={t.ReplaceableId?'Team picture '+t.ReplaceableId:'Picture '+(i+1)} selected={i===emitter.TextureID} onClick={()=>patch({TextureID:i,ReplaceableId:0})}/>)}</div>{model.Textures.length>pictureLimit&&<button onClick={()=>setPictureLimit(n=>n+64)}>More pictures</button>}<button onClick={onImport}>Load picture…</button><button onClick={()=>onTeamPicture(1)}>Team color</button><button onClick={()=>onTeamPicture(2)}>Team glow</button></details>
  <canvas className="pe-picture-grid" ref={canvas} width="256" height="256" aria-label="Picture frame grid" role="button" tabIndex={0} onClick={e=>{if(!visibleGrid)return;const rect=e.currentTarget.getBoundingClientRect(),cell=particleCellAt(e.clientX-rect.left,e.clientY-rect.top,rect.width,rect.height,rows,columns),next=new Uint32Array(values);next[endpoint]=cell+(endpoint===1?1:0);update(group,next);}} onKeyDown={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const next=new Uint32Array(values),delta=e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:e.key==='ArrowDown'?columns:-columns;next[endpoint]=Math.max(0,Math.min(rows*columns-(endpoint===1?0:1),next[endpoint]+delta));update(group,next);}}}/>
  {!visibleGrid&&<small>Grid exceeds the visible cell budget. Exact values remain available in Classic.</small>}
  <div className="pe-grid-dimensions"><label>Rows <button aria-label="Remove picture row" disabled={rows<=1} onClick={()=>grid(rows-1,columns)}>−</button><output>{rows}</output><button aria-label="Add picture row" onClick={()=>grid(rows+1,columns)}>+</button></label><label>Columns <button aria-label="Remove picture column" disabled={columns<=1} onClick={()=>grid(rows,columns-1)}>−</button><output>{columns}</output><button aria-label="Add picture column" onClick={()=>grid(rows,columns+1)}>+</button></label></div>
  {pending&&<div className="pe-grid-confirm" role="alert"><span>{pending.invalid.join(', ')} exceed the new grid.</span><button onClick={()=>{patch(particleGridChange(emitter,pending.rows,pending.columns,{correct:true}).values);setPending(null);}}>Change grid and bound these ranges</button><button onClick={()=>setPending(null)}>Cancel grid change</button></div>}
  <label>Picture frames<select aria-label="Picture frame group" value={group} onChange={e=>setGroup(e.target.value)}>{particleFrameGroups.map(([name,field])=><option key={field} value={field}>{name}</option>)}</select></label><div className="pe-frame-endpoints">{['First cell','Through cell'].map((name,i)=><button key={name} aria-pressed={endpoint===i} onClick={()=>setEndpoint(i)}>{name} · {i===1&&values[1]>values[0]?values[1]-1:values[i]}</button>)}</div>
  <ParticleSlider label="Frame repeats" field={group} min={0} max={10} step={1} value={values[2]} begin={()=>begin(group,{raw:true})} change={value=>change(new Uint32Array([values[0],values[1],value]))} {...{finish,cancel}}/>
  <label>Draw as<select aria-label="Draw as" value={emitter.FrameFlags} onChange={e=>update('FrameFlags',Number(e.target.value))}><option value={1}>Sprites</option><option value={2}>Streaks</option><option value={3}>Both</option></select></label>
  <label>Blend look<select aria-label="Blend look" value={emitter.FilterMode} onChange={e=>update('FilterMode',Number(e.target.value))}>{particleBlendNames.map((name,i)=><option key={name} value={i}>{name}</option>)}</select></label><button onClick={()=>setCompare({source:structuredClone(model),sequence,time:frame})}>Compare blend looks</button>
  {compare&&<ParticleBlendComparisons {...compare} id={emitter.ObjectId} {...{assets,preferences}} onChoose={value=>{update('FilterMode',value);setCompare(null);}} onClose={()=>setCompare(null)}/>}
  <details><summary>Orientation and draw options</summary><div className="pe-timing-mode"><button aria-pressed={!!(emitter.Flags&524288)} onClick={()=>update('Flags',emitter.Flags|524288)}>Carry particles</button><button aria-pressed={!(emitter.Flags&524288)} onClick={()=>update('Flags',emitter.Flags&~524288)}>Leave behind</button></div><div className="pe-timing-mode"><button aria-pressed={!(emitter.Flags&1048576)} onClick={()=>update('Flags',emitter.Flags&~1048576)}>Face camera</button><button aria-pressed={!!(emitter.Flags&1048576)} onClick={()=>update('Flags',emitter.Flags|1048576)}>Flat</button></div>{onDemo&&<button aria-pressed={demo} onClick={()=>onDemo(!demo)}>Demonstration motion</button>}{[['Keep brightness',32768],['Ignore fog',262144],['Sort distant particles',65536]].map(([name,bit])=><button key={bit} aria-pressed={!!(emitter.Flags&bit)} onClick={()=>update('Flags',emitter.Flags^bit)}>{name}</button>)}</details>
  {message&&<small role="status">{message}</small>}
 </div>;
}
