import React,{Suspense,lazy,useCallback,useEffect,useRef,useState} from 'react';
import {openDocument} from '../src/editor-document.js';
import {activeParticleSample} from '../src/particle-sampling.js';
const GamePreview=lazy(()=>import('./GamePreview.jsx'));
/** Explicit context inspection never installs the source into the Lab or model session. */
export default function ParticleSourceContext({item,preferences,onClose}){
 const [sourceIndex,setSourceIndex]=useState(0),[source,setSource]=useState(null),[error,setError]=useState(''),[sequence,setSequence]=useState(0),[time,setTime]=useState(0),[playing,setPlaying]=useState(true),capture=useRef(null);
 useEffect(()=>{let live=true;setSource(null);setError('');window.desktop.particleSourceContext({id:item.id,sourceIndex}).then(record=>{if(!live)return;const doc=openDocument(new Uint8Array(record.bytes),record.name),sample=activeParticleSample(doc.model);setSequence(sample.sequence);setTime(sample.time);setSource({...record,model:doc.model,assets:new Map(record.assets.map(asset=>[asset.name.replaceAll('/','\\').toLowerCase(),asset]))});}).catch(error=>{if(live)setError(error.message);});return()=>{live=false;};},[item.id,sourceIndex]);
 const ready=useCallback(api=>{capture.current=api;if(api)api.whenReady().catch(error=>setError(error.message));},[]);
 return <div className="pe-source-context" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}}} role="dialog" aria-label="Source context"><header><strong>{item.name} · source context</strong><button onClick={onClose}>Close source context</button></header><select aria-label="Source association" value={sourceIndex} onChange={e=>setSourceIndex(Number(e.target.value))}>{item.sources.map((s,i)=><option key={i} value={i}>{s.logicalPath||'Source '+(i+1)}</option>)}</select>{error&&<p role="status">{error}</p>}{source?<><div className="pe-source-stage"><Suspense fallback={<span>Loading preview…</span>}><GamePreview key={sourceIndex} presentation="preview" model={source.model} textureAssets={source.assets} preferences={preferences} particleAuthoring sequenceIndex={sequence} time={time} onTimeChange={setTime} playing={playing} onPlayingChange={setPlaying} showParticles showGrid mode="textured" view="perspective" onCaptureReady={ready}/></Suspense></div><div className="pe-transport"><button onClick={()=>setPlaying(v=>!v)}>{playing?'Pause source':'Play source'}</button><input aria-label="Source playhead" type="range" min={source.model.Sequences[sequence]?.Interval[0]||0} max={source.model.Sequences[sequence]?.Interval[1]||1000} value={time} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><button onClick={()=>capture.current?.fit()}>Fit source</button></div><select aria-label="Source animation" value={sequence} onChange={e=>{const i=Number(e.target.value);setSequence(i);setTime(source.model.Sequences[i].Interval[0]);}}>{source.model.Sequences.map((s,i)=><option key={i} value={i}>{s.Name}</option>)}</select>{source.missing.length>0&&<details><summary>{source.missing.length} missing pictures</summary>{source.missing.map(name=><p key={name}>{name}</p>)}</details>}{(source.unsupported.modelParticles+source.unsupported.popcorn)>0&&<small>Incomplete context preview: {source.unsupported.modelParticles} model emitters and {source.unsupported.popcorn} Popcorn emitters are not simulated.</small>}</>:!error&&<p>Loading source context…</p>}</div>;
}
