import React from 'react';
import { Section, TextField, NumberField, SelectField, Check, TrackEditor } from './Fields.jsx';
import { particleAnimatedParameters, particleUVGroups, particleFlags, particleRotationDegrees, setParticleRotationDegrees } from '../src/particle-editing.js';
const labelFor = property => property.replace(/([a-z])([A-Z])/g, '$1 $2');
const colorHex = color => '#' + Array.from(color || [1,1,1], value => Math.round(Math.min(1,Math.max(0,value))*255).toString(16).padStart(2,'0')).join('');
export default function ParticleClassicControls({model,emitter,frame,sequence,update,apply,onImportTexture}) {
 const emitterId=emitter.ObjectId, angles=particleRotationDegrees(model,emitter,frame,sequence);
 const arrayValue=(property,index,value,Type,fallback)=>{const values=Array.from(emitter[property]||fallback);values[index]=value;update(property,new Type(values));};
 return <><Section open={false} title="Emitter"><TextField label="Name" value={emitter.Name} onChange={value => update('Name', value)}/><div className="pe-axis-fields" data-particle-rotation>{['X', 'Y', 'Z'].map((axis, index) => <NumberField key={axis} label={`Rotate ${axis} (degrees)`} value={Number(angles[index].toFixed(3))} onChange={value => { const next = [...angles]; next[index] = value; apply(`Rotate particle ${axis}`, current => setParticleRotationDegrees(current, emitterId, frame, sequence, next)); }}/>)}</div><div className="pe-axis-fields">{['X', 'Y', 'Z'].map((axis, index) => <NumberField key={axis} label={`Position ${axis}`} value={emitter.PivotPoint?.[index] || 0} onChange={value => apply(`Move particle ${axis}`, current => { const node = current.ParticleEmitters2.find(item => item.ObjectId === emitterId), next = new Float32Array(node.PivotPoint || [0, 0, 0]); next[index] = value; node.PivotPoint = next; current.PivotPoints[node.ObjectId] = next; }, ['Nodes', 'PivotPoints'])}/>)}</div></Section>
          <Section open={false} title="Animated parameters"><div className="pe-parameters">{particleAnimatedParameters.map(property => <TrackEditor key={`${emitterId}:${property}`} label={labelFor(property)} value={emitter[property]} defaultValue={property === 'Visibility' ? 1 : 0} frame={frame} globalSequences={model.GlobalSequences} onChange={value => update(property, value)}/>)}</div></Section>
          <Section open={false} title="Rendering"><SelectField label="Texture ID" value={emitter.TextureID ?? ''} options={[{ label: 'No texture', value: '' }, ...model.Textures.map((texture, value) => ({ value, label: `${value} · ${texture.Image || `Replaceable ${texture.ReplaceableId}`}` }))]} onChange={value => update('TextureID', value === '' ? null : Number(value))}/>{onImportTexture && <button onClick={onImportTexture}>Load texture…</button>}<SelectField label="Filter Mode" value={emitter.FilterMode ?? 0} options={['Blend', 'Additive', 'Modulate', 'Modulate 2×', 'Alpha Key'].map((label, value) => ({ label, value }))} onChange={value => update('FilterMode', Number(value))}/></Section>
          <Section open={false} title="Segments"><div className="pe-segments">{[0, 1, 2].map(index => <fieldset key={index}><legend>Segment {index + 1}</legend><label className="field"><span>Color</span><input aria-label={`Segment ${index + 1} color`} type="color" value={colorHex(emitter.SegmentColor?.[index])} onChange={event => { const colors = (emitter.SegmentColor || [[1, 1, 1], [1, 1, 1], [1, 1, 1]]).map(value => new Float32Array(value)); colors[index] = new Float32Array([1, 3, 5].map(start => parseInt(event.target.value.slice(start, start + 2), 16) / 255)); update('SegmentColor', colors); }}/></label><NumberField label={`Alpha ${index + 1} (0–255)`} min={0} max={255} step={1} value={emitter.Alpha?.[index] ?? 255} onChange={value => arrayValue('Alpha', index, value, Uint8Array, [255, 255, 0])}/><NumberField label={`Scaling ${index + 1}`} min={0} value={emitter.ParticleScaling?.[index] ?? 1} onChange={value => arrayValue('ParticleScaling', index, value, Float32Array, [1, 1, 1])}/></fieldset>)}</div></Section>
          <Section open={false} title="Head and tail animation"><div className="pe-uv-groups">{particleUVGroups.map(([label, property]) => <fieldset key={property}><legend>{label}</legend>{['Start', 'End', 'Repeat'].map((field, index) => <NumberField key={field} label={`${label} ${field}`} min={0} step={1} value={emitter[property]?.[index] ?? (index === 2 ? 1 : 0)} onChange={value => arrayValue(property, index, value, Uint32Array, [0, 0, 1])}/>)}</fieldset>)}</div></Section>
          <Section open={false} title="Flags"><div className="checks">{particleFlags.map(([label, bit]) => <Check key={bit} label={label} value={(emitter.Flags || 0) & bit} onChange={value => update('Flags', value ? (emitter.Flags || 0) | bit : (emitter.Flags || 0) & ~bit)}/>)}<span title="Alpha Key is the particle filter mode in MDX; this checkbox and Filter Mode edit the same setting."><Check label="Alpha Key" value={emitter.FilterMode === 4} onChange={value => update('FilterMode', value ? 4 : 0)}/></span><Check label="Squirt" value={emitter.Squirt} onChange={value => update('Squirt', value)}/>{[['Head', 1], ['Tail', 2]].map(([label, bit]) => <Check key={bit} label={label} value={(emitter.FrameFlags || 0) & bit} onChange={value => update('FrameFlags', value ? (emitter.FrameFlags || 0) | bit : (emitter.FrameFlags || 0) & ~bit)}/>)}</div></Section>
          <Section open={false} title="Miscellaneous">{['Rows', 'Columns', 'LifeSpan', 'TailLength', 'PriorityPlane', 'ReplaceableId', 'Time'].map(property => <NumberField key={property} label={property === 'ReplaceableId' ? 'Replaceable ID' : labelFor(property)} step={['Rows', 'Columns', 'PriorityPlane', 'ReplaceableId'].includes(property) ? 1 : 'any'} min={['Rows', 'Columns'].includes(property) ? 1 : property === 'PriorityPlane' ? undefined : 0} max={property === 'Time' ? 1 : undefined} value={emitter[property] ?? 0} onChange={value => update(property, value)}/>)}<p className="hint">Time is the fraction of each particle's lifespan spent in the first segment. The preview Frame control chooses animation time.</p></Section></>;
}
