import React,{Suspense,lazy,useMemo,useRef,useState} from 'react';
import {placeTimedParticleRecipe} from '../src/particle-placement.js';
const GamePreview=lazy(()=>import('./GamePreview.jsx'));
export default function ParticlePlacementStage({doc,recipe,placement,onPosition,onEnd,textureAssets,preferences,teamColor,onError}){
 const [snapshot,setSnapshot]=useState(null),[surface,setSurface]=useState(false),[time,setTime]=useState(placement.from||0),[playing,setPlaying]=useState(true),[speed,setSpeed]=useState(.5),drag=useRef(null);
 const graph=useMemo(()=>{
  try{const model=structuredClone(doc.model),inserted=placeTimedParticleRecipe(model,recipe,placement,{preview:true});
   return {model,...inserted};
  }catch(error){return {error:error.message};}
 },[doc,doc.revision,recipe,placement.parent,placement.sequence,placement.fit,placement.motion,placement.from,placement.to,placement.sequences]);
 React.useEffect(()=>{onError?.(graph.error||'');if(graph.interval)setTime(value=>Math.max(graph.interval[0],Math.min(graph.interval[1],value)));},[graph]);
 if(graph.error)return <div className="pe-placement-error" role="status">{graph.error}</div>;
 const anchor=graph.model.Helpers.find(n=>n.ObjectId===graph.anchorId);
 anchor.Translation={LineType:0,GlobalSeqId:null,Keys:[{Frame:graph.interval[0],Vector:new Float32Array(placement.position)}]};
 const stop=()=>{drag.current=null;},clip=doc.model.Sequences[placement.sequence]?.Interval||graph.interval;
 return <>
 <Suspense fallback={<span>Preparing placement…</span>}><GamePreview presentation="preview" model={graph.model} particleAuthoring particleLiveModel={graph.model} particleLiveRevision={placement.position.join(':')} particleLiveField="Translation" particleSelectedId={graph.ids[0]} particleAnchorId={graph.anchorId} onParticleStage={setSnapshot} onParticleSurfacePlace={surface?point=>{onPosition(point);setSurface(false);}:undefined} textureAssets={textureAssets} preferences={preferences} teamColor={teamColor} sequenceIndex={doc.model.Sequences.length?placement.sequence:-1} time={time} onTimeChange={setTime} playing={playing} playbackSpeed={speed*100} showParticles showGrid mode="textured" view="perspective" overlays={{bones:false,nodes:false,particles:false,attachments:false}}/></Suspense>
 {!placement.ribbon&&snapshot?.anchor&&<svg className="pe-stage-tools" viewBox={'0 0 '+snapshot.width+' '+snapshot.height} aria-label="Placement ghost"><g role="slider" tabIndex={0} aria-label="Move effect anchor" onPointerDown={e=>{e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);drag.current={x:e.clientX,y:e.clientY,position:[...placement.position],basis:structuredClone(snapshot.anchor)};}} onPointerMove={e=>{const d=drag.current;if(d)onPosition(d.position.map((v,i)=>v+(e.clientX-d.x)*d.basis.dx[i]+(e.clientY-d.y)*d.basis.dy[i]));}} onPointerUp={stop} onPointerCancel={()=>{if(drag.current)onPosition(drag.current.position);stop();}} onKeyDown={e=>{if(e.key==='Escape'&&drag.current){e.stopPropagation();onPosition(drag.current.position);stop();}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();onPosition(placement.position.map((v,i)=>v+(e.key==='ArrowRight'?10:e.key==='ArrowLeft'?-10:0)*snapshot.anchor.dx[i]+(e.key==='ArrowDown'?10:e.key==='ArrowUp'?-10:0)*snapshot.anchor.dy[i]));}}}><circle cx={snapshot.anchor.point[0]} cy={snapshot.anchor.point[1]} r="10"/><text x={snapshot.anchor.point[0]+14} y={snapshot.anchor.point[1]-12}>Placement ghost</text></g></svg>}
 {!placement.ribbon&&<div className="pe-placement-overlay"><div className="pe-transport"><button onClick={()=>setPlaying(v=>!v)}>{playing?'Pause ghost':'Play ghost'}</button><input aria-label="Placement playhead" type="range" min={clip[0]} max={clip[1]} step="1" value={Math.max(clip[0],Math.min(clip[1],time))} onChange={e=>{setPlaying(false);setTime(Number(e.target.value));}}/><select aria-label="Placement speed" value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.1,.25,.5,1].map(value=><option key={value} value={value}>{value}×</option>)}</select>{doc.model.Sequences.length>0&&<button onClick={()=>{setPlaying(false);onEnd(Math.round(time));}}>End here</button>}</div>{!placement.ribbon&&<div><button aria-pressed={surface} onClick={()=>setSurface(v=>!v)}>{surface?'Double-click a surface':'Snap to surface'}</button></div>}</div>}
 {placement.ribbon&&snapshot?.guide?.upper&&<svg className="pe-stage-tools pe-ribbon-fit-guide" viewBox={'0 0 '+snapshot.width+' '+snapshot.height} aria-label="Fitted weapon edge"><line x1={snapshot.guide.lower[0]} y1={snapshot.guide.lower[1]} x2={snapshot.guide.upper[0]} y2={snapshot.guide.upper[1]}/><text x={snapshot.guide.upper[0]+10} y={snapshot.guide.upper[1]}>Fitted edge</text></svg>}
 </>;
}
