import React,{Suspense,lazy,useCallback,useMemo,useRef,useState} from 'react';
import {particleExampleNames,particleExamplePair} from '../src/particle-examples.js';
import {starterTextureAsset,STARTER_TEXTURE} from '../src/particle-starters.js';
import {particleRecipeDocument} from '../src/particle-recipes.js';
import {addParticleDemonstration} from '../src/particle-sweep.js';
const GamePreview=lazy(()=>import('./GamePreview.jsx'));
function Pair({pairs,time,preferences,dark,onChoose}){
 const [index,setIndex]=useState(0),[images,setImages]=useState({}),[error,setError]=useState(''),busy=useRef(false),camera=useRef(null),assets=useMemo(()=>new Map([[STARTER_TEXTURE.toLowerCase(),starterTextureAsset()]]),[]);
 const model=useMemo(()=>{if(index>=pairs.length)return null;const next=particleRecipeDocument(pairs[index].recipe).model;if(pairs[index].motion)addParticleDemonstration(next,[0,5000]);return next;},[pairs,index]);
 const prefs=useMemo(()=>({...preferences,graphics:{...preferences.graphics,pauseWhenHidden:false},viewportAppearance:{...preferences.viewportAppearance,background:{type:'color',color:dark?'#24282c':'#d0d0d0'}}}),[preferences,dark]);
 const ready=useCallback(async api=>{if(!api||busy.current||index>=pairs.length)return;busy.current=true;try{await api.whenReady();if(camera.current)api.setCameraView(camera.current);else {api.fit();camera.current=api.cameraView();}const image=api.captureFrame({maxDimension:400}).toDataURL('image/png');setImages(old=>({...old,[index]:image}));}catch(e){setError(e.message);}finally{busy.current=false;setIndex(n=>n+1);}},[index,pairs]);
 return <><div className="pe-example-pair">{pairs.map((pair,i)=><div key={i}><strong>{pair.label}</strong><div className="pe-example-image" style={{background:dark?'#24282c':'#d0d0d0'}}>{images[i]?<img src={images[i]} alt={pair.label}/>:<span>Rendering…</span>}</div><button onClick={()=>onChoose(structuredClone(pair.recipe))}>Open this example</button></div>)}</div>{error&&<p role="status">{error}</p>}{model&&<div className="pe-example-renderer" aria-hidden="true"><Suspense fallback={null}><GamePreview key={index} presentation="preview" model={model} textureAssets={assets} preferences={prefs} particleAuthoring particleSelectedId={pairs[index].motion?(model.ParticleEmitters2[0]?.ObjectId??model.RibbonEmitters[0]?.ObjectId):undefined} particleSweepRange={pairs[index].motion?[0,5000]:undefined} sequenceIndex={0} time={time} playing={false} showParticles showGrid={false} mode="textured" view="perspective" onCaptureReady={ready}/></Suspense></div>}</>;
}
export default function ParticleExampleComparison({preferences,onChoose,onClose}){
 const [kind,setKind]=useState('smoke'),[moment,setMoment]=useState(1),[dark,setDark]=useState(true),example=useMemo(()=>particleExamplePair(kind),[kind]);
 return <div className="pe-example-comparison" role="dialog" aria-label="Particle examples" onKeyDown={e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}}}><header><strong>MDLxL original examples</strong><button onClick={onClose}>Close examples</button></header><nav aria-label="Example type">{particleExampleNames.map(([id,label])=><button key={id} aria-pressed={kind===id} onClick={()=>setKind(id)}>{label}</button>)}</nav><div className="pe-example-moments">{example.times.map((time,i)=><button key={i} aria-pressed={i===moment} onClick={()=>setMoment(i)}>{(time/1000).toFixed(1)} s</button>)}<button onClick={()=>setDark(v=>!v)}>{dark?'Light background':'Dark background'}</button></div><Pair key={kind+':'+moment+':'+dark} pairs={example.pairs} time={example.times[moment]} {...{preferences,dark,onChoose}}/>{kind==='sweep'&&<small>The same demonstration motion is shown on both sides. It is not saved with either recipe.</small>}</div>;
}
