import React, { useMemo, useState } from 'react';
import { previewShape, resolveShapeSelection, SHAPE_TOOLS } from '../src/shaping.js';
import ForgePreview from './ForgePreview.jsx';
import './forge.css';
const HELP = { Bend: 'Curve the selection from its minimum edge.', Warp: 'Twist the selection around the chosen axis.', Dome: 'Raise the center with a smooth dome; amount is in model units.', Wrap: 'Wrap the selection into a centered circular arc.', Taper: 'Resize the cross section progressively along the chosen axis.' };
export default function ShapingDialog({ model, selectedGeosets, selectionByGeoset = {}, initialTool = 'Bend', onClose, onApply }) {
  const [tool, setTool] = useState(initialTool), [axis, setAxis] = useState(initialTool === 'Dome' ? 2 : 1), [amount, setAmount] = useState(0), [wire, setWire] = useState(false), [message, setMessage] = useState('');
  const selection = useMemo(() => resolveShapeSelection(model, selectedGeosets, selectionByGeoset), [model, selectedGeosets, selectionByGeoset]);
  const preview = useMemo(() => { try { const result = previewShape(model, selection, { tool, axis, amount }); return { geosets: Object.keys(selection).map(i => result.Geosets[i]) }; } catch (error) { return { error: error.message, geosets: [] }; } }, [model, selection, tool, axis, amount]);
  const apply = async () => { try { const result = await onApply({ tool, axis, amount }, selection); if (result !== false) onClose(); } catch (error) { setMessage(error.message); } };
  const dragAmount = value => setAmount(Math.round(Math.max(tool === 'Taper' ? -95 : tool === 'Dome' ? -100 : -360, Math.min(tool === 'Taper' ? 200 : tool === 'Dome' ? 100 : 360, value))));
  return <div className="forge-overlay" onKeyDown={e => { e.stopPropagation(); if (e.key === 'Escape') onClose(); }}><section className="forge-shape-dialog" role="dialog" aria-modal="true" aria-label="Shape geosets"><header><h2>Shape geosets</h2><button onClick={onClose} aria-label="Close shaping tools">✕</button></header><div className="forge-shape-body"><aside><label>Tool<select value={tool} onChange={e => { setTool(e.target.value); setAmount(0); if (e.target.value === 'Dome') setAxis(2); }}>{SHAPE_TOOLS.map(t => <option key={t}>{t}</option>)}</select></label><p>{HELP[tool]}</p><label>Axis<select value={axis} onChange={e => setAxis(+e.target.value)}>{['X', 'Y', 'Z'].map((a, i) => <option value={i} key={a}>{a}</option>)}</select></label><label>{tool === 'Taper' ? 'Amount (%)' : tool === 'Dome' ? 'Height' : 'Angle (degrees)'}<input type="number" value={amount} onChange={e => setAmount(+e.target.value)}/></label><input type="range" min={tool === 'Taper' ? -95 : tool === 'Dome' ? -100 : -360} max={tool === 'Taper' ? 200 : tool === 'Dome' ? 100 : 360} value={amount} onChange={e => setAmount(+e.target.value)} aria-label="Shaping amount"/><label className="forge-check"><input type="checkbox" checked={wire} onChange={e => setWire(e.target.checked)}/>Wireframe</label><button onClick={() => setAmount(0)}>Reset preview</button><p>Selected geosets share one deformation box. Selected vertices take priority when present.</p><p>Apply creates one undo step.</p>{(preview.error || message) && <p role="alert" className="forge-error">{preview.error || message}</p>}</aside><ForgePreview geosets={preview.geosets} wire={wire} shapeHandle={{amount,onChange:dragAmount}}/></div><footer><button onClick={onClose}>Cancel</button><button className="forge-primary" disabled={!!preview.error || amount === 0} onClick={apply}>Apply</button></footer></section></div>;
}
