// Dependency-free search shared by the offline app and its audits.
export const GROUPS = [
 {id:'metal',name:'Metal & armour',hint:'Plate, chain, blades, fittings',tags:['plate','chain','chain-links','scale-armour','blades','metal','gold','rust'],sample:'footman'},
 {id:'body',name:'Bodies & faces',hint:'Human, orc, elf, undead',tags:['human-body','orc-body','elf-body','undead-body','demon-body','troll-body','naga-body','ogre-body','dwarf-body','tauren-body','draenei-body','face','skin','hair'],sample:'peasant'},
 {id:'cloth',name:'Cloth & leather',hint:'Fabric, straps, robes, banners',tags:['cloth','leather','rope','banner','team-color'],sample:'priest'},
 {id:'wood',name:'Wood & structures',hint:'Planks, bark, beams, roofs',tags:['wood','bark','roof','straw'],sample:'crates'},
 {id:'stone',name:'Stone & earth',hint:'Masonry, rock, dirt, tiles',tags:['stone','brick','rock','dirt','sand','tiles','rune'],sample:'ruins'},
 {id:'creature',name:'Beasts & bones',hint:'Fur, scales, wings, skulls',tags:['fur','scales','feathers','bone','horn','wing','chitin'],sample:'wolf'},
 {id:'nature',name:'Nature & terrain',hint:'Leaves, grass, water, snow',tags:['foliage','grass','water','ice','snow','lava','crystal','coral'],sample:'lordaeron'},
 {id:'effects',name:'Magic & effects',hint:'Fire, glow, smoke, particles',tags:['fire','glow','smoke','lightning','blood','magic','shadow'],sample:'fire'},
 {id:'detail',name:'Symbols & surfaces',hint:'Eyes, emblems, gems, patterns',tags:['eye','emblem','gem','pattern','glass','paper'],sample:'book'},
 {id:'interface',name:'Interface & artwork',hint:'Icons, frames, menus, scenes',tags:['icon','frame','button','text','artwork','cursor','minimap','background','pathing'],sample:'humanuitile'}
];
export const LABELS = {'human-body':'Human body','orc-body':'Orc body','elf-body':'Elf body','undead-body':'Undead body','demon-body':'Demon body','troll-body':'Troll body','naga-body':'Naga body','ogre-body':'Ogre body','dwarf-body':'Dwarf body','tauren-body':'Tauren body','draenei-body':'Draenei body','chain-links':'Chains & links','hair':'Hair & beards','scale-armour':'Scale armour','team-color':'Team-colour candidates',coral:'Coral',pathing:'Pathing masks',plate:'Plate armour',chain:'Chainmail',blades:'Blades & weapons',metal:'Metal fittings',gold:'Gold & brass',rust:'Rust & weathering',face:'Faces',skin:'Skin',cloth:'Cloth',leather:'Leather',rope:'Rope',banner:'Banners',wood:'Planks & timber',bark:'Bark',roof:'Roofing',straw:'Straw & thatch',stone:'Stonework',brick:'Brick',rock:'Rock',dirt:'Earth & dirt',sand:'Sand',tiles:'Tiles',rune:'Runes',fur:'Fur',scales:'Scales',feathers:'Feathers',bone:'Bone & skulls',horn:'Horns & tusks',wing:'Wings',chitin:'Chitin & shells',foliage:'Leaves & plants',grass:'Grass',water:'Water',ice:'Ice',snow:'Snow',lava:'Lava',crystal:'Crystal',fire:'Fire',glow:'Glows',smoke:'Smoke & clouds',lightning:'Lightning',blood:'Blood',magic:'Magic',shadow:'Shadows',eye:'Eyes',emblem:'Emblems',gem:'Gems',pattern:'Patterns',glass:'Glass',paper:'Paper & pages',icon:'Icons',frame:'Borders & frames',button:'Buttons',text:'Text & lettering',artwork:'Painted artwork',cursor:'Cursors',minimap:'Minimap',background:'Backgrounds'};
export const KINDS = {all:'Any source',units:'Units & characters',buildings:'Buildings',doodads:'Doodads & props',terrain:'Terrain',effects:'Spells & effects',ui:'Menus & interface',icons:'Icons',campaign:'Campaign',cinematic:'Cinematics',other:'Other native assets'};
export const aliases = {
 metal:['plate','chain','chain-links','scale-armour','blades','metal','gold','rust'],armour:['plate','chain','scale-armour'],armor:['plate','chain','scale-armour'],armored:['plate','chain','scale-armour'],armoured:['plate','chain','scale-armour'],steel:['plate','blades','metal'],iron:['plate','chain','metal'],silver:['plate','chain','metal'],mail:['chain'],chainmail:['chain'],chain:['chain','chain-links'],chains:['chain-links'],links:['chain-links'],platemail:['plate'],plate:['plate'],sword:['blades'],swords:['blades'],blade:['blades'],weapon:['blades'],weapons:['blades'],axe:['blades'],axes:['blades'],spear:['blades'],hammer:['blades'],shield:['plate','blades'],shields:['plate','blades'],metallic:['plate','chain','chain-links','scale-armour','blades','metal','gold','rust'],skin:['skin','human-body','orc-body','elf-body','undead-body','demon-body','troll-body','naga-body','ogre-body','dwarf-body','tauren-body','draenei-body'],hair:['hair'],beard:['hair'],beards:['hair'],scalemail:['scale-armour'],gold:['gold'],brass:['gold'],copper:['gold'],rusty:['rust'],
 dwarf:['dwarf-body'],dwarves:['dwarf-body'],tauren:['tauren-body'],draenei:['draenei-body'],human:['human-body'],humans:['human-body'],orc:['orc-body'],orcs:['orc-body'],elf:['elf-body'],elves:['elf-body'],nightelf:['elf-body'],bloodelf:['elf-body'],undead:['undead-body'],zombie:['undead-body'],demon:['demon-body'],demons:['demon-body'],troll:['troll-body'],trolls:['troll-body'],naga:['naga-body'],ogre:['ogre-body'],ogres:['ogre-body'],body:['human-body','orc-body','elf-body','undead-body','demon-body','troll-body','naga-body','ogre-body','dwarf-body','tauren-body','draenei-body','skin'],bodies:['skin','human-body','orc-body','elf-body','undead-body'],flesh:['skin','human-body','orc-body','elf-body','undead-body','demon-body','troll-body','naga-body','ogre-body','dwarf-body','tauren-body','draenei-body'],face:['face'],faces:['face'],head:['face'],hands:['skin'],
 fabric:['cloth'],cloth:['cloth','banner'],robe:['cloth'],robes:['cloth'],cape:['cloth'],clothing:['cloth','leather'],flag:['banner'],flags:['banner'],banners:['banner'],strap:['leather'],straps:['leather'],belt:['leather'],hide:['leather','fur'],teamcolor:['team-color'],teamcolour:['team-color'],
 wood:['wood','bark'],wooden:['wood','bark'],plank:['wood'],planks:['wood'],timber:['wood'],beam:['wood'],beams:['wood'],tree:['bark','foliage'],trees:['bark','foliage'],thatch:['straw'],roof:['roof','straw'],stone:['stone','brick','rock','tiles'],masonry:['stone','brick'],wall:['stone','brick','wood'],earth:['dirt','sand','rock'],ground:['dirt','sand','grass','rock','snow','tiles'],
 animal:['fur','scales','feathers','horn','wing','chitin'],beast:['fur','scales','feathers','horn','wing','chitin'],beasts:['fur','scales','feathers','horn','wing','chitin'],bone:['bone'],bones:['bone'],skull:['bone'],skulls:['bone'],skeleton:['bone','undead-body'],tusk:['horn'],tusks:['horn'],horns:['horn'],wings:['wing'],feather:['feathers'],scale:['scales'],shell:['chitin'],
 nature:['foliage','grass','bark','water','ice','snow','rock'],leaf:['foliage'],leaves:['foliage'],plant:['foliage'],plants:['foliage'],vegetation:['foliage','grass'],foliage:['foliage'],frozen:['ice','snow'],ocean:['water'],river:['water'],water:['water'],
 magic:['magic','glow','lightning','fire','rune'],spell:['magic','glow','lightning','fire'],glowing:['glow'],flame:['fire'],flames:['fire'],flaming:['fire'],electric:['lightning'],cloud:['smoke'],fog:['smoke'],smoke:['smoke'],jewel:['gem','crystal'],jewels:['gem','crystal'],gems:['gem'],symbol:['emblem','rune'],symbols:['emblem','rune'],book:['paper'],parchment:['paper'],border:['frame'],borders:['frame'],portrait:['face','artwork'],icon:['icon'],icons:['icon'],menu:['background','frame','button','text','artwork'],interface:['frame','button','text','cursor','minimap','background'],ui:['frame','button','text','cursor','minimap','background'],
};
export const kindAliases={unit:'units',units:'units',character:'units',characters:'units',building:'buildings',buildings:'buildings',structure:'buildings',structures:'buildings',doodad:'doodads',doodads:'doodads',props:'doodads',terrain:'terrain',tileset:'terrain',tilesets:'terrain',effect:'effects',effects:'effects',campaign:'campaign',cinematic:'cinematic',cinematics:'cinematic',movie:'cinematic'};

