// Query aliases only: catalog names, paths, metadata and authored model data
// retain their original spelling. English queries remain usable in both UI languages.
const aliases = new Map();
const add = (english, russian) => russian.split('|').forEach(word => aliases.set(word, english));
const adjective = (english, stem) => add(english, ['ый','ий','ой','ая','яя','ое','ее','ые','ие','ых','их','ую','юю','ого','его','ой','ей','ым','им','ыми','ими','ом','ем'].map(ending => stem + ending).join('|'));
for (const [english, stem] of [
  ['rusty','ржав'],['old','стар'],['ancient','древн'],['weathered','обветренн'],['worn','потерт'],['torn','рван'],['rotten','гнил'],['blighted','оскверненн'],['mossy','мшист'],['moldy','плесневел'],['cracked','треснувш'],['broken','сломанн'],['damaged','поврежденн'],['scratched','поцарапанн'],['dented','помят'],['dirty','грязн'],['bloody','кровав'],['burnt','обгорел'],['clean','чист'],['polished','полированн'],['rough','груб'],['smooth','гладк'],['wet','мокр'],['dry','сух'],['dark','темн'],['light','светл'],['bright','ярк'],['ornate','украшенн'],['carved','резн'],['spiked','шипаст'],['transparent','прозрачн'],['seamless','бесшовн'],
  ['red','красн'],['blue','син'],['blue','голуб'],['green','зелен'],['yellow','желт'],['orange','оранжев'],['purple','фиолетов'],['pink','розов'],['black','черн'],['white','бел'],['gray','сер'],['brown','коричнев'],['gold','золот'],['silver','серебрян'],['wood','деревянн'],['stone','каменн'],['metal','металлическ'],['leather','кожан'],['cloth','тканев'],['iron','железн'],['steel','стальн'],['bone','костян'],['skeletal','скелетн'],['poisonous','ядовит'],['frozen','ледян'],
]) adjective(english, stem);
for (const [english, russian] of [
  ['metal','металл|металла|металлы'],['iron','железо|железа'],['steel','сталь|стали'],['gold','золото|золота'],['silver','серебро|серебра'],['rusty','ржавчина|ржавчины'],['armour','броня|брони|доспех|доспехи|доспехов'],['chainmail','кольчуга|кольчуги|кольчугу|кольчужная броня'],['plate','латы|латная броня|латные доспехи'],['scalemail','чешуйчатая броня'],['chains','цепь|цепи|цепей'],
  ['cloth','ткань|ткани|тканей'],['leather','кожа|кожи'],['skin','кожа тела'],['fur','мех|меха|шерсть|шерсти'],['rope','веревка|веревки|канат|канаты'],['banner','знамя|знамена|флаг|флаги'],['wood','дерево|дерева|древесина'],['bark','кора|коры'],['planks','доска|доски|досок|балки'],['roof','крыша|крыши|кровля'],['straw','солома|соломы'],['stone','камень|камня|камни|камней'],['brick','кирпич|кирпичи|кирпичная кладка'],['rock','скала|скалы'],['dirt','земля|земли|грязь'],['sand','песок|песка'],['tiles','плитка|плитки'],
  ['bone','кость|кости|костей'],['skull','череп|черепа|черепов'],['horn','рог|рога|рогов|бивни'],['wing','крыло|крылья|крыльев'],['feathers','перо|перья|перьев'],['scales','чешуя|чешуи'],['chitin','хитин|панцирь|панцири'],['foliage','листва|листья|растения'],['grass','трава|травы'],['water','вода|воды'],['ice','лед|льда'],['snow','снег|снега'],['lava','лава|лавы'],['crystal','кристалл|кристаллы'],['fire','огонь|огня|пламя'],['smoke','дым|дыма|облака'],['lightning','молния|молнии'],['blood','кровь|крови'],['magic','магия|магии'],['glow','свечение'],['shadow','тень|тени'],['rune','руна|руны'],['emblem','эмблема|эмблемы|герб|гербы'],['glass','стекло|стекла'],['paper','бумага|бумаги|пергамент'],['gem','самоцвет|самоцветы'],
  ['sword','меч|мечи|мечей'],['axe','топор|топоры|топоров'],['spear','копье|копья|копий|алебарда'],['hammer','молот|молоты|булава'],['dagger','кинжал|кинжалы|нож|ножи'],['shield','щит|щиты|щитов'],['bow','лук|луки|стрелы'],['gun','ружье|ружья|винтовка|пушка|пушки'],['staff','посох|посохи'],['helmet','шлем|шлемы'],['shoulder','наплечник|наплечники'],['glove','перчатка|перчатки|рукавицы'],['boot','сапоги|обувь'],['face','лицо|лица'],['hair','волосы|борода|бороды'],['eye','глаз|глаза'],['body','тело|тела'],['stitched','швы|шов|стежки'],['riveted','заклепки|заклепка'],['spiked','шипы|шипов'],['trim','ободок|окантовка|кайма'],['nail','гвоздь|гвозди|гвоздей'],
  ['human','человек|люди|людей'],['orc','орк|орки|орков'],['elf','эльф|эльфы|эльфов'],['night elf','ночной эльф|ночные эльфы|ночных эльфов'],['blood elf','эльф крови|эльфы крови|эльфов крови'],['undead','нежить|нежити'],['demon','демон|демоны|демонов'],['dwarf','гном|гномы|гномов|дворф|дворфы'],['troll','тролль|тролли|троллей'],['tauren','таурен|таурены|тауренов'],['naga','нага|наги'],['ogre','огр|огры'],['draenei','дреней|дренеи'],['knight','рыцарь|рыцари'],['paladin','паладин'],['footman','пехотинец'],['grunt','бугай'],['ghoul','вурдалак'],['abomination','поганище|мясник'],['skeleton','скелет|скелеты'],
  ['nurgle','нургл|нургла'],['khorne','кхорн|кхорна'],['tzeentch','тзинч|тзинча'],['slaanesh','слаанеш'],['warhammer chaos','хаос вархаммер|хаос warhammer'],['skaven','скавен|скавены'],['bretonnia','бретонния'],['warhammer empire','империя вархаммер'],['greenskins','зеленокожие'],['tomb kings','цари гробниц'],['vampire counts','графы вампиры|графы-вампиры'],['mordor','мордор|мордора'],['isengard','изенгард'],['rohan','рохан'],['gondor','гондор'],['nazgul','назгул|назгулы'],['balrog','балрог'],['high elves','высшие эльфы'],['dark elves','темные эльфы'],['wood elves','лесные эльфы'],['warhammer dwarf','гномы вархаммер'],['warhammer fantasy','вархаммер'],['lord of the rings','властелин колец|средиземье|средиземья|толкин'],
  ['units','юниты|персонажи'],['buildings','здания|строения'],['doodads','декорации'],['terrain','ландшафт|рельеф'],['effects','эффекты'],['icons','иконки|значки'],['team color','цвет команды|командный цвет'],['without','без|кроме'],['not','не'],['or','или'],['with','с'],['and','и'],['looking for','ищу|найти|нужна|нужен|нужны'],['texture','текстура|текстуры|текстуру'],
]) add(english, russian);

const escape = value => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const pattern = new RegExp('(?<![\\p{L}\\p{N}_])(?:' + [...aliases.keys()].sort((a,b) => b.length-a.length).map(escape).join('|') + ')(?![\\p{L}\\p{N}_])', 'giu');

export function russianTextureQuery(query) {
  const value = String(query || '');
  if (!/[а-яё]/i.test(value)) return value;
  // Protect explicit paths and quoted/name literals from semantic rewriting.
  if (/[\\/]|\.(?:blp|dds|png|tga|jpg|jpeg|bmp)\b/i.test(value) && !/\s/.test(value)) return value;
  return value.split(/((?:name|path):(?:"[^"]*"|[^\s]+)|"[^"]*")/gi).map((part,i) => i % 2 ? part : part.normalize('NFC').replace(/ё/gi,'е').replace(pattern, word => aliases.get(word.toLowerCase()))).join('');
}
